### ISSUE TITLE
english version , please

### ISSUE THREAD

**Issue by ingnelson** [proxysu/windows#10]
Hello. 

Many people around the world would like to use your program.

could you add a english version,  please. or a tap where the client can chose Chinese or English, please

**Comment by proxysu** [comment]
Ok i try

**Comment by xenstar** [comment]
Yes, please add the english version. 

Plz plz plz

**Comment by proxysu** [comment]
https://github.com/proxysu/windows/releases/tag/v2.0.0
增加多语言，支持 Englis、简体中文、正体（繁体）中文。
Multi-language support, Englis, Simplified Chinese, and Traditional (Traditional) Chinese are supported.
The English interface is made by Google Translate, please understand if it is inappropriate
