### ISSUE TITLE
能否添加密钥登录ssh？

### ISSUE THREAD

**Issue by yyuurrii34** [proxysu/windows#13]
如题

**Comment by proxysu** [comment]
可以，原来一开始有密钥登录项，后来觉得用处不大，就去掉了，如果有需要，可以再启用。

**Comment by proxysu** [comment]
现在正在添加有关SS及其插件的一键安装，等完成后。一起发布新版本，添加密钥登录。

**Comment by renweikg1** [comment]
> 现在正在添加有关SS及其插件的一键安装，等完成后。一起发布新版本，添加密钥登录。

甲骨文vps用户表示：不加没法用！！

**Comment by proxysu** [comment]
已添加密钥登录功能，目前还不支持putty格式的密钥。
https://github.com/proxysu/windows/releases/tag/v2.2.0

**Comment by Alvin9999** [comment]
@proxysu SSR不能选加密方式,希望以后可以像SS一样选加密方式

**Comment by Alvin9999** [comment]
ping 域名 -c 1 | grep -oE -m1 "([0-9]{1,3}\.){3}[0-9]{1,3}"
ip

搭建trojan-go老是提示域名未能解析到ip,但从界面看命令是解析出来了ip的,把命令在vps服务器里面进行输入也能解析到ip.可能哪里有问题哦

**Comment by hexiyou** [comment]
> ping 域名 -c 1 | grep -oE -m1 "([0-9]{1,3}.){3}[0-9]{1,3}"
> ip
> 
> 搭建trojan-go老是提示域名未能解析到ip,但从界面看命令是解析出来了ip的,把命令在vps服务器里面进行输入也能解析到ip.可能哪里有问题哦

是不是VPS禁ping，导致命令返回超时了。

**Comment by Alvin9999** [comment]
> > ping 域名 -c 1 | grep -oE -m1 "([0-9]{1,3}.){3}[0-9]{1,3}"
> > ip
> > 搭建trojan-go老是提示域名未能解析到ip,但从界面看命令是解析出来了ip的,把命令在vps服务器里面进行输入也能解析到ip.可能哪里有问题哦
> 
> 是不是VPS禁ping，导致命令返回超时了。

没有禁ping,可以ping通的

**Comment by Alvin9999** [comment]
尝试了多次后，现在可以了，是有点奇怪。

**Comment by proxysu** [comment]
是VPS的DNS缓存问题，再遇到这种情况，可以重启一下VPS,一般就没问题了。

**Comment by proxysu** [comment]
> @proxysu SSR不能选加密方式,希望以后可以像SS一样选加密方式

我调整一下。

**Comment by Alvin9999** [comment]
> 是VPS的DNS缓存问题，再遇到这种情况，可以重启一下VPS,一般就没问题了。

OK

**Comment by Alvin9999** [comment]
> 是VPS的DNS缓存问题，再遇到这种情况，可以重启一下VPS,一般就没问题了。

因为我遇到了这种情况很多次，不同的服务器，也许其他人也会遇到类似的情况。以后可否加DNS清理缓存的命令在软件中。

**Comment by proxysu** [comment]
嗯，可以的。

**Comment by Alvin9999** [comment]
> 嗯，可以的。
> 不过，这个可能在某些情况下，不起作用，比如，DNS解析生效缓慢，这个由机房所在的地区与所用 的DNS解析服务有关。这种情况下，就是清空了本地的DNS缓存也没用，只能多等待一些时候，等DNS解析真正生效。

好的，知道了。最近给项目点星的人很多啊，要火的节奏。

**Comment by Alvin9999** [comment]
@proxysu 个人的建议，如果能做到，软件又会上一个台阶。现在功能其实很多的，能够搭建的工具有很多可以选择。更多的要考虑不同的使用场景，因为很多人还有一定的搭建基础，很多的服务器是搭建过工具的，二次搭建报错的问题如果能解决就更好。还有一个就是如果搭建报错，增加卸载功能，不然大家又要用SSH工具去连接vps。最终软件能彻底摆脱不用SSH工具去连接vps就会大大方便用户。相当于无论是新手还是老手，只要用这个工具就可以了。当然，过程还是很辛苦也会很花时间。

**Comment by kingming200** [comment]
膜拜大佬，小白福音，注意安全

**Comment by proxysu** [comment]
> @proxysu 个人的建议，如果能做到，软件又会上一个台阶。现在功能其实很多的，能够搭建的工具有很多可以选择。更多的要考虑不同的使用场景，因为很多人还有一定的搭建基础，很多的服务器是搭建过工具的，二次搭建报错的问题如果能解决就更好。还有一个就是如果搭建报错，增加卸载功能，不然大家又要用SSH工具去连接vps。最终软件能彻底摆脱不用SSH工具去连接vps就会大大方便用户。相当于无论是新手还是老手，只要用这个工具就可以了。当然，过程还是很辛苦也会很花时间。

这个功能正在添加中，下一个版本，就会增加卸载功能。

**Comment by proxysu** [comment]
> @proxysu SSR不能选加密方式,希望以后可以像SS一样选加密方式

这个SSR的加密方式，我看了一下，因为很长时间没人维护，都是已经不再推荐的了。原因是特征明显，改变加密方式，感觉没什么意义。原教程里面，这里选择的是none。所以这个SSR目前先保留这样吧。
原教程：https://blog.duyuanchao.me/posts/a384749f/

**Comment by Alvin9999** [comment]
> > @proxysu SSR不能选加密方式,希望以后可以像SS一样选加密方式
> 
> 这个SSR的加密方式，我看了一下，因为很长时间没人维护，都是已经不再推荐的了。原因是特征明显，改变加密方式，感觉没什么意义。原教程里面，这里选择的是none。所以这个SSR目前先保留这样吧。
> 原教程：https://blog.duyuanchao.me/posts/a384749f/

不套caddy,普通的SSR加密方式能否增加? 现在用普通SSR加密方式也很多,网上也有很多免费SSR帐号,活的挺好的

**Comment by Alvin9999** [comment]
SSR用户基数还是大,套caddy需要域名,对于有的小白用户来说还不会,可以增加普通方式,降低一点门槛,当然caddy方式也保留,个人建议,供参考

**Comment by proxysu** [comment]
> @proxysu 个人的建议，如果能做到，软件又会上一个台阶。现在功能其实很多的，能够搭建的工具有很多可以选择。更多的要考虑不同的使用场景，因为很多人还有一定的搭建基础，很多的服务器是搭建过工具的，二次搭建报错的问题如果能解决就更好。还有一个就是如果搭建报错，增加卸载功能，不然大家又要用SSH工具去连接vps。最终软件能彻底摆脱不用SSH工具去连接vps就会大大方便用户。相当于无论是新手还是老手，只要用这个工具就可以了。当然，过程还是很辛苦也会很花时间。

卸载功能已添加。
https://github.com/proxysu/windows/releases/tag/v2.2.3

**Comment by proxysu** [comment]
> SSR用户基数还是大,套caddy需要域名,对于有的小白用户来说还不会,可以增加普通方式,降低一点门槛,当然caddy方式也保留,个人建议,供参考

好吧，我调整一下，SSR的相关参数。

**Comment by wangzhiyong2019** [comment]
无论安装哪种代理都一直报错：安装caddy失败
安装Caddy......
yum install yum-plugin-copr -y
Loaded plugins: copr, fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.hostduplex.com
 * elrepo: elrepo.0m3n.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirror.web-ster.com
 * updates: mirrors.radwebhosting.com
Package yum-plugin-copr-1.1.31-54.el7_8.noarch already installed and latest version
Nothing to do

yum copr enable @caddy/caddy -y
Loaded plugins: copr, fastestmirror
copr done

yum -y -q install caddy
Package caddy-2.2.0-1.el7.x86_64 already installed and latest version

find / -name caddy
/etc/caddy
/var/lib/caddy
/usr/share/bash-completion/completions/caddy
/usr/share/caddy

安装Caddy失败！

**Comment by proxysu** [comment]
你是用的CentOS7吗？你换成CentOS 8或者其他版本的linux发行版试试。这个Caddy v2好像对CentOS 7不太兼容，容易出错，有可能是CentOS 7 有的VPS少依赖。

**Comment by wangzhiyong2019** [comment]
> 你是用的CentOS7吗？你换成CentOS 8或者其他版本的linux发行版试试。这个Caddy v2好像对CentOS 7不太兼容，容易出错，有可能是CentOS 7 有的VPS少依赖。

我确实是CentOS7，换其他系统试试，谢谢
