### ISSUE TITLE
V2ray一键安装出错

### ISSUE THREAD

**Issue by LoveLoliii** [proxysu/windows#15]
显示安装失败.脚本运行出错。
日志如下：
```
yes | bash /tmp/go.sh -f
info: Installing V2Ray v4.28.2 for x86_64
Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.28.2/v2ray-linux-64.zip
Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.28.2/v2ray-linux-64.zip.dgst
error: Check failed! Please check your network or try again.
```
vps 是jp节点的vultr服务器，之前部署过ssr，v2ray。

**Comment by mjkillly** [comment]
the same error

**Comment by Alvin9999** [comment]
使用提醒：
ProxySU的安装流程，是假设在全新系统下，没有装过以上代理软件，如果已经安装过，最好将系统重装一下，会减少很多的麻烦。ProxySU在开发过程中，一般都是在vultr的vps中测试，测试系统版本为：Centos7/8 Debian9/10 Ubuntu18.04/20.04。

**Comment by Alvin9999** [comment]
目前软件还在完善中,建议全新系统来使用软件

**Comment by proxysu** [comment]
> 显示安装失败.脚本运行出错。
> 日志如下：
> 
> ```
> yes | bash /tmp/go.sh -f
> info: Installing V2Ray v4.28.2 for x86_64
> Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.28.2/v2ray-linux-64.zip
> Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.28.2/v2ray-linux-64.zip.dgst
> error: Check failed! Please check your network or try again.
> ```
> 
> vps 是jp节点的vultr服务器，之前部署过ssr，v2ray。

这是V2ray官方脚本的问题，现在已经修复了。应该没问题了。
https://github.com/v2fly/fhs-install-v2ray/issues/132
