### ISSUE TITLE
安装的是trojan-go，装好后出来的链接和二维码，都是trojan的

### ISSUE THREAD

**Issue by cn-404-not-found** [proxysu/windows#17]
大神有空检查下？

**Comment by proxysu** [comment]
好的，谢谢提醒。

**Comment by proxysu** [comment]
> 大神有空检查下？

你使用的是哪个客户端？Qv2ray吗？

**Comment by proxysu** [comment]
这个版本，已经更新Trojan-go的分享链接，
https://github.com/proxysu/windows/releases/tag/v2.4.2
使用这个标准：
https://github.com/p4gefau1t/trojan-go/issues/132

**Comment by cn-404-not-found** [comment]
> > 大神有空检查下？
> 
> 你使用的是哪个客户端？Qv2ray吗？

是的，用Qv2ray

**Comment by proxysu** [comment]
v2.4.2+版本，可以使用
