### ISSUE TITLE
ssh-rsa 密钥登陆 谷歌云 直接闪退

### ISSUE THREAD

**Issue by FayeMa3** [proxysu/windows#19]
ssh-rsa 密钥登陆直接闪退 能否支持一下呢。

**Comment by proxysu** [comment]
ProxySU目前还只支持openssh格式的密钥，其他格式的，需要先转换一下，很快就会添加兼容共他格式密钥的功能。

**Comment by hujiao80** [comment]
登录甲骨文，家里的本子也是闪退，在办公室的电脑上就一切正常，都是win10

**Comment by lbbboy** [comment]
> ProxySU目前还只支持openssh格式的密钥，其他格式的，需要先转换一下，很快就会添加兼容共他格式密钥的功能。

已经转了还是闪退！后缀有限制吗？

**Comment by lbbboy** [comment]
---- END SSH2 ENCRYPTED PRIVATE KEY ----

要这个格式！已经可以了。

**Comment by spearsh** [comment]
提一个比较小白的问题，要使用谷歌云，但是不知道怎么找到安装中对应root的那个密码?
Connecting to instances as the root user 里有提示，但是看不懂，能否指导一下？

**Comment by proxysu** [comment]
这个需要手动启用。可以谷歌一下。
关键字搜索：谷歌云开启root 密码登录

**Comment by spearsh** [comment]
十分感谢大佬的指点，昨天试了，按照网上的教程顺利开启谷歌云的root登录，然后安装成功，随后的设置也是按照油管里的教程，但是最后没有握手成功，用v2rayN打开sockets服务后，就显示无法连接。可能是安装naiveproxy-v86.0.4240文件时出现问题，因为刚开始没有找到正确的安装文件，刚开始好像是下载安装了source文件，所以下载完成后解压一看里面的文件跟油管教程里显示的不一样，所以又删掉，然后回github再找到客户端文件下载安装，后面的都是按照视频里的操作的，但是最后好像不行，握手失败。

**Comment by spearsh** [comment]
不知道问题出在哪里

**Comment by proxysu** [comment]
如果这个模式不行，可以试一下其他代理模式。
