### ISSUE TITLE
能否在trojan-go的安装设置中增加多路复用的选项

### ISSUE THREAD

**Issue by lancehzzz1202** [proxysu/windows#21]
首先感谢大佬提供这么好用的软件。
问题如下：
现在多路复用还需要手动修改一下配置文件，且重启后trojan-go总是需要手动systemctl restart一下。能否在安装时增加一项多路复用的可选配置。这样可以使得配置更加便捷，更加方便像我这类小白用户的使用。

**Comment by proxysu** [comment]
可以啊，我尽可能快的添加。

**Comment by heartnn** [comment]
多路复用在clash下会有问题，windows的客户端没问题，但linux_x64下的docker直接连不上，还是慎用为好。仅对于目前clash版本，不表示将来会有问题。

**Comment by proxysu** [comment]
我在添加这个功能的时候发现，启用多路复用，无需在服务器上设置，只需设置客户端配置。服务端会自动适配。

**Comment by proxysu** [comment]
https://github.com/proxysu/windows/releases/tag/v2.4.16
这个版本在客户端，添加了多路复用，不过，只在客户端配置有效，服务端无需配置，自动适配。

**Comment by lancehzzz1202** [comment]
按照官方解释确实如此，当时我是被油管的up主误导了。感谢大佬。
