### ISSUE TITLE
ProxySu 2.3在搬瓦工Centos7和Ubuntu中安装Trojan-go,caddy都启动失败

### ISSUE THREAD

**Issue by lqhorochi** [proxysu/windows#22]
ProxySu 2.3在搬瓦工Centos7和Ubuntu中安装Trojan-go,caddy都启动失败
是脚本问题还是???

**Comment by winhkey** [comment]
改用2.2.3版本也同样无法启动caddy

**Comment by proxysu** [comment]
有什么错误提示吗？可以把中间窗口的信息，去除IP和域名后，复制到这里。我排除一下，问题。

**Comment by proxysu** [comment]
另外可以试试Debian9或者10。

**Comment by lhy0838** [comment]
同样状况，就是第一次启动失败，然后第二次启动也失败，然后退出

**Comment by pandy003** [comment]
正在登錄遠程主機......
主機登錄成功!
檢測是否運行在root權限下...
id -u
0

檢測結果：OK！
檢測系統是否已經安裝V2ray......
find / -name v2ray

檢測結果：未安裝V2Ray!
檢測系統是否符合安裝要求......
uname -r
4.19.0-10-cloud-amd64

command -v apt
/usr/bin/apt

command -v dnf

command -v yum

command -v zypper

command -v systemctl
/bin/systemctl

command -v getenforce

檢測結果：OK!
校對時間......
時間差符合要求，OK!
系統環境檢測完畢，符合安裝要求,開始佈署......
開啟防火牆相應端口......
系統環境檢測完畢，符合安裝要求,開始佈署......
正在安裝V2Ray......
curl -o /tmp/go.sh https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh

yes | bash /tmp/go.sh -f
info: Installing V2Ray v4.30.0 for x86_64
Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.30.0/v2ray-linux-64.zip
Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.30.0/v2ray-linux-64.zip.dgst
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libarchive13 libicu63 libxml2
Suggested packages:
  lrzip
The following NEW packages will be installed:
  libarchive-tools libarchive13 libicu63 libxml2
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 9378 kB of archives.
After this operation, 35.4 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libicu63 amd64 63.1-6+deb10u1 [8300 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libxml2 amd64 2.9.4+dfsg1-7+b3 [687 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 libarchive13 amd64 3.3.3-4+deb10u1 [313 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 libarchive-tools amd64 3.3.3-4+deb10u1 [77.2 kB]
Fetched 9378 kB in 1s (14.5 MB/s)
Selecting previously unselected package libicu63:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 37801 files and directories currently installed.)
Preparing to unpack .../libicu63_63.1-6+deb10u1_amd64.deb ...
Unpacking libicu63:amd64 (63.1-6+deb10u1) ...
Selecting previously unselected package libxml2:amd64.
Preparing to unpack .../libxml2_2.9.4+dfsg1-7+b3_amd64.deb ...
Unpacking libxml2:amd64 (2.9.4+dfsg1-7+b3) ...
Selecting previously unselected package libarchive13:amd64.
Preparing to unpack .../libarchive13_3.3.3-4+deb10u1_amd64.deb ...
Unpacking libarchive13:amd64 (3.3.3-4+deb10u1) ...
Selecting previously unselected package libarchive-tools.
Preparing to unpack .../libarchive-tools_3.3.3-4+deb10u1_amd64.deb ...
Unpacking libarchive-tools (3.3.3-4+deb10u1) ...
Setting up libicu63:amd64 (63.1-6+deb10u1) ...
Setting up libxml2:amd64 (2.9.4+dfsg1-7+b3) ...
Setting up libarchive13:amd64 (3.3.3-4+deb10u1) ...
Setting up libarchive-tools (3.3.3-4+deb10u1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
info: libarchive-tools is installed.
info: Extract the V2Ray package to /tmp/tmp.7nW52Ba1D3 and prepare it for installation.
info: Systemd service files have been installed successfully!
warning: The following are the actual parameters for the v2ray service startup.
warning: Please make sure the configuration file path is correctly set.
# /etc/systemd/system/v2ray.service
[Unit]
Description=V2Ray Service
Documentation=https://www.v2fly.org/
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
Restart=on-failure
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
# In case you have a good reason to do so, duplicate this file in the same directory and make your customizes there.
# Or all changes you made will be lost!  # Refer: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
[Service]
ExecStart=
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
installed: /usr/local/bin/v2ray
installed: /usr/local/bin/v2ctl
installed: /usr/local/share/v2ray/geoip.dat
installed: /usr/local/share/v2ray/geosite.dat
installed: /usr/local/etc/v2ray/config.json
installed: /var/log/v2ray/
installed: /var/log/v2ray/access.log
installed: /var/log/v2ray/error.log
installed: /etc/systemd/system/v2ray.service
installed: /etc/systemd/system/v2ray@.service
removed: /tmp/tmp.7nW52Ba1D3
info: V2Ray v4.30.0 is installed.
You may need to execute a command to remove dependent software: apt purge curl unzip
Please execute the command: systemctl enable v2ray; systemctl start v2ray

rm -f /tmp/go.sh

find / -name v2ray
/usr/local/etc/v2ray
/usr/local/share/v2ray
/usr/local/bin/v2ray
/var/log/v2ray

V2ray安裝成功！
systemctl enable v2ray

mv /usr/local/etc/v2ray/config.json /usr/local/etc/v2ray/config.json.1

安裝完畢，上傳配置文件......
正在啟動V2ray......
systemctl restart v2ray

ps aux | grep v2ray
nobody    3135  1.6  0.6 4915748 25960 ?       Ssl  02:18   0:00 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
root      3146  0.0  0.0   5404  2936 ?        Ss   02:18   0:00 bash -c ps aux | grep v2ray
root      3148  0.0  0.0   4836   888 ?        S    02:18   0:00 grep v2ray

V2ray啟動成功！
BBR測試......
uname -r
4.19.0-10-cloud-amd64

sysctl net.ipv4.tcp_congestion_control | grep bbr

正在啟用BBR......
bash -c 'echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf'

bash -c 'echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf'

sysctl -p
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

sysctl net.ipv4.tcp_congestion_control | grep bbr
net.ipv4.tcp_congestion_control = bbr

BBR 啟用成功！
生成客戶端配置......
V2Ray安裝成功,祝你玩的愉快！ ！
正在登錄遠程主機......
主機登錄成功!
檢測是否運行在root權限下...
id -u
0

檢測結果：OK！
檢測系統是否已經安裝V2ray......
find / -name v2ray

檢測結果：未安裝V2Ray!
檢測系統是否符合安裝要求......
uname -r
4.19.0-10-cloud-amd64

command -v apt
/usr/bin/apt

command -v dnf

command -v yum

command -v zypper

command -v systemctl
/bin/systemctl

command -v getenforce

檢測結果：OK!
校對時間......
時間差符合要求，OK!
正在檢測域名是否解析到當前VPS的IP上......
curl -4 ip.sb
xx.xxx.xxx.x

ping xx.xxxx.xx -c 1 | grep -oE -m1 "([0-9]{1,3}\.){3}[0-9]{1,3}"
xx.xxx.xxx.x

解析正確！ OK!
apt -qq update
5 packages can be upgraded. Run 'apt list --upgradable' to see them.

apt -y -qq install lsof
Suggested packages:
  perl
The following NEW packages will be installed:
  lsof
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 319 kB of archives.
After this operation, 465 kB of additional disk space will be used.
Selecting previously unselected package lsof.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 37801 files and directories currently installed.)
Preparing to unpack .../lsof_4.91+dfsg-1_amd64.deb ...
Unpacking lsof (4.91+dfsg-1) ...
Setting up lsof (4.91+dfsg-1) ...
Processing triggers for man-db (2.8.5-2) ...

檢測端口占用情況......
lsof -n -P -i :80 | grep LISTEN

lsof -n -P -i :443 | grep LISTEN

檢測結果：未被佔用！
系統環境檢測完畢，符合安裝要求,開始佈署......
開啟防火牆相應端口......
系統環境檢測完畢，符合安裝要求,開始佈署......
正在安裝V2Ray......
curl -o /tmp/go.sh https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh

yes | bash /tmp/go.sh -f
info: Installing V2Ray v4.30.0 for x86_64
Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.30.0/v2ray-linux-64.zip
Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.30.0/v2ray-linux-64.zip.dgst
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libarchive13 libicu63 libxml2
Suggested packages:
  lrzip
The following NEW packages will be installed:
  libarchive-tools libarchive13 libicu63 libxml2
0 upgraded, 4 newly installed, 0 to remove and 5 not upgraded.
Need to get 9378 kB of archives.
After this operation, 35.4 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libicu63 amd64 63.1-6+deb10u1 [8300 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libxml2 amd64 2.9.4+dfsg1-7+b3 [687 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 libarchive13 amd64 3.3.3-4+deb10u1 [313 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 libarchive-tools amd64 3.3.3-4+deb10u1 [77.2 kB]
Fetched 9378 kB in 1s (14.5 MB/s)
Selecting previously unselected package libicu63:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 37827 files and directories currently installed.)
Preparing to unpack .../libicu63_63.1-6+deb10u1_amd64.deb ...
Unpacking libicu63:amd64 (63.1-6+deb10u1) ...
Selecting previously unselected package libxml2:amd64.
Preparing to unpack .../libxml2_2.9.4+dfsg1-7+b3_amd64.deb ...
Unpacking libxml2:amd64 (2.9.4+dfsg1-7+b3) ...
Selecting previously unselected package libarchive13:amd64.
Preparing to unpack .../libarchive13_3.3.3-4+deb10u1_amd64.deb ...
Unpacking libarchive13:amd64 (3.3.3-4+deb10u1) ...
Selecting previously unselected package libarchive-tools.
Preparing to unpack .../libarchive-tools_3.3.3-4+deb10u1_amd64.deb ...
Unpacking libarchive-tools (3.3.3-4+deb10u1) ...
Setting up libicu63:amd64 (63.1-6+deb10u1) ...
Setting up libxml2:amd64 (2.9.4+dfsg1-7+b3) ...
Setting up libarchive13:amd64 (3.3.3-4+deb10u1) ...
Setting up libarchive-tools (3.3.3-4+deb10u1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
info: libarchive-tools is installed.
info: Extract the V2Ray package to /tmp/tmp.46xyzOSMLp and prepare it for installation.
info: Systemd service files have been installed successfully!
warning: The following are the actual parameters for the v2ray service startup.
warning: Please make sure the configuration file path is correctly set.
# /etc/systemd/system/v2ray.service
[Unit]
Description=V2Ray Service
Documentation=https://www.v2fly.org/
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
Restart=on-failure
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
# In case you have a good reason to do so, duplicate this file in the same directory and make your customizes there.
# Or all changes you made will be lost!  # Refer: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
[Service]
ExecStart=
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
installed: /usr/local/bin/v2ray
installed: /usr/local/bin/v2ctl
installed: /usr/local/share/v2ray/geoip.dat
installed: /usr/local/share/v2ray/geosite.dat
installed: /usr/local/etc/v2ray/config.json
installed: /var/log/v2ray/
installed: /var/log/v2ray/access.log
installed: /var/log/v2ray/error.log
installed: /etc/systemd/system/v2ray.service
installed: /etc/systemd/system/v2ray@.service
removed: /tmp/tmp.46xyzOSMLp
info: V2Ray v4.30.0 is installed.
You may need to execute a command to remove dependent software: apt purge curl unzip
Please execute the command: systemctl enable v2ray; systemctl start v2ray

rm -f /tmp/go.sh

find / -name v2ray
/usr/local/etc/v2ray
/usr/local/share/v2ray
/usr/local/bin/v2ray
/var/log/v2ray

V2ray安裝成功！
systemctl enable v2ray

mv /usr/local/etc/v2ray/config.json /usr/local/etc/v2ray/config.json.1

安裝完畢，上傳配置文件......
安裝Caddy......
echo "deb [trusted=yes] https://apt.fury.io/caddy/ /" | tee -a /etc/apt/sources.list.d/caddy-fury.list
deb [trusted=yes] https://apt.fury.io/caddy/ /

apt install -y apt-transport-https
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 149 kB of archives.
After this operation, 156 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 apt-transport-https all 1.8.2.1 [149 kB]
Fetched 149 kB in 0s (1886 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 37871 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.8.2.1_all.deb ...
Unpacking apt-transport-https (1.8.2.1) ...
Setting up apt-transport-https (1.8.2.1) ...

apt -qq update
5 packages can be upgraded. Run 'apt list --upgradable' to see them.

apt -y -qq install caddy
The following NEW packages will be installed:
  caddy
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 11.5 MB of archives.
After this operation, 33.1 MB of additional disk space will be used.
Selecting previously unselected package caddy.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 37875 files and directories currently installed.)
Preparing to unpack .../archives/caddy_2.2.0_amd64.deb ...
Unpacking caddy (2.2.0) ...
Setting up caddy (2.2.0) ...
Created symlink /etc/systemd/system/multi-user.target.wants/caddy.service → /lib/systemd/system/caddy.service.

find / -name caddy
/usr/share/caddy
/usr/bin/caddy
/etc/bash_completion.d/caddy
/etc/caddy
/var/lib/caddy
/var/lib/caddy/.config/caddy

Caddy安裝成功！
systemctl enable caddy

正在為Http2Web模式升級Caddy v2.2.0測試版！
curl -o /tmp/caddy.zip https://raw.githubusercontent.com/proxysu/Resources/master/Caddy2/caddy.zip

yes | unzip -o /tmp/caddy.zip

chmod +x caddy

systemctl stop caddy;rm -f /usr/bin/caddy

cp /root/caddy /usr/bin/

rm -f /tmp/caddy.zip caddy

上傳Caddy配置文件......
mv /etc/caddy/Caddyfile /etc/caddy/Caddyfile.bak

sed -i 's/8800/8800/' /etc/caddy/Caddyfile

sed -i 's/##domain##/xx.xxxx.xx/g' /etc/caddy/Caddyfile

sed -i 's/##path##/\/ray/' /etc/caddy/Caddyfile

Caddy配置文件上傳成功,OK!
正在啟動Caddy......
systemctl restart caddy

ps aux | grep caddy
root      2260  0.0  0.0   5404  2944 ?        Ss   02:28   0:00 bash -c ps aux | grep caddy
root      2262  0.0  0.0   4836   884 ?        S    02:28   0:00 grep caddy

Caddy啟動失敗！
正在啟動Caddy（第二次嘗試）！
systemctl restart caddy

ps aux | grep caddy
root      2267  0.0  0.0   5404  2960 ?        Ss   02:28   0:00 bash -c ps aux | grep caddy
root      2269  0.0  0.0   4836   880 ?        S    02:28   0:00 grep caddy

Caddy啟動失敗(第二次)！退出安裝！

**Comment by proxysu** [comment]
是不是域名申请次数过多，被限制频次了。可以更换一个域名，或者增加子域名试试。

**Comment by lhy0838** [comment]
换了子域名还是同样的状况

**Comment by proxysu** [comment]
Let's Encrypt 的证书服务器，好像对于申请的主机IP也有限制，如果同一主机IP。在短时间内，过于频繁的申请证书，就会被限制。这个时间，更换任何域名，都不能申请成功。不知你们遇到的是不是这种情况。
如果caddy启动失败可以用以下命令，查看失败的原因:
journalctl --boot -u caddy.service

**Comment by wuaini10001** [comment]
你们搬瓦工速度快吗用这个我的慢的像条狗

**Comment by proxysu** [comment]
这个版本，增加了查看启动出错的信息显示，
https://github.com/proxysu/windows/releases/tag/v2.4.3

**Comment by proxysu** [comment]
> 你们搬瓦工速度快吗用这个我的慢的像条狗

这个与个人所在地区的线路有关

**Comment by lqhorochi** [comment]
> 这个版本，增加了查看启动出错的信息显示，
> https://github.com/proxysu/windows/releases/tag/v2.4.3

ok.试一下.还有一个问题需要咨询,proxysu中有没有卸载非proxysu脚本安装的ss,ssr,v2ray,Trojan等的功能
有些人不想重新系统,直接使用proxysu安装,但是系统又安装了其他脚本,又想卸载之前的脚本.

**Comment by lhy0838** [comment]
相关日志：
caddy启动失败(第二次)！退出安装！
journalctl -n50 --no-pager --boot -u  caddy
-- Logs begin at Tue 2020-10-13 00:51:12 EDT, end at Tue 2020-10-13 00:54:59 EDT. --
Oct 13 00:54:49 Private-1 systemd[1]: Started Caddy.
Oct 13 00:54:49 Private-1 systemd[1]: Starting Caddy...
Oct 13 00:54:49 Private-1 caddy[13550]: caddy.HomeDir=/var/lib/caddy
Oct 13 00:54:49 Private-1 caddy[13550]: caddy.AppDataDir=/var/lib/caddy/.local/share/caddy
Oct 13 00:54:49 Private-1 caddy[13550]: caddy.AppConfigDir=/var/lib/caddy/.config/caddy
Oct 13 00:54:49 Private-1 caddy[13550]: caddy.ConfigAutosavePath=/var/lib/caddy/.config/caddy/autosave.json
Oct 13 00:54:49 Private-1 caddy[13550]: caddy.Version=v2.2.0
Oct 13 00:54:49 Private-1 caddy[13550]: runtime.GOOS=linux
Oct 13 00:54:49 Private-1 caddy[13550]: runtime.GOARCH=amd64
Oct 13 00:54:49 Private-1 caddy[13550]: runtime.Compiler=gc
Oct 13 00:54:49 Private-1 caddy[13550]: runtime.NumCPU=1
Oct 13 00:54:49 Private-1 caddy[13550]: runtime.GOMAXPROCS=1
Oct 13 00:54:49 Private-1 caddy[13550]: runtime.Version=go1.15
Oct 13 00:54:49 Private-1 caddy[13550]: os.Getwd=/
Oct 13 00:54:49 Private-1 caddy[13550]: LANG=en_US.UTF-8
Oct 13 00:54:49 Private-1 caddy[13550]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Oct 13 00:54:49 Private-1 caddy[13550]: HOME=/var/lib/caddy
Oct 13 00:54:49 Private-1 caddy[13550]: LOGNAME=caddy
Oct 13 00:54:49 Private-1 caddy[13550]: USER=caddy
Oct 13 00:54:49 Private-1 caddy[13550]: SHELL=/sbin/nologin
Oct 13 00:54:49 Private-1 caddy[13550]: {"level":"info","ts":1602564889.908556,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Oct 13 00:54:49 Private-1 caddy[13550]: {"level":"info","ts":1602564889.9117527,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
Oct 13 00:54:49 Private-1 caddy[13550]: {"level":"info","ts":1602564889.9121177,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv1","http_port":80}
Oct 13 00:54:49 Private-1 systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Oct 13 00:54:49 Private-1 systemd[1]: Unit caddy.service entered failed state.
Oct 13 00:54:49 Private-1 systemd[1]: caddy.service failed.
Oct 13 00:54:59 Private-1 systemd[1]: Started Caddy.
Oct 13 00:54:59 Private-1 systemd[1]: Starting Caddy...
Oct 13 00:54:59 Private-1 caddy[13570]: caddy.HomeDir=/var/lib/caddy
Oct 13 00:54:59 Private-1 caddy[13570]: caddy.AppDataDir=/var/lib/caddy/.local/share/caddy
Oct 13 00:54:59 Private-1 caddy[13570]: caddy.AppConfigDir=/var/lib/caddy/.config/caddy
Oct 13 00:54:59 Private-1 caddy[13570]: caddy.ConfigAutosavePath=/var/lib/caddy/.config/caddy/autosave.json
Oct 13 00:54:59 Private-1 caddy[13570]: caddy.Version=v2.2.0
Oct 13 00:54:59 Private-1 caddy[13570]: runtime.GOOS=linux
Oct 13 00:54:59 Private-1 caddy[13570]: runtime.GOARCH=amd64
Oct 13 00:54:59 Private-1 caddy[13570]: runtime.Compiler=gc
Oct 13 00:54:59 Private-1 caddy[13570]: runtime.NumCPU=1
Oct 13 00:54:59 Private-1 caddy[13570]: runtime.GOMAXPROCS=1
Oct 13 00:54:59 Private-1 caddy[13570]: runtime.Version=go1.15
Oct 13 00:54:59 Private-1 caddy[13570]: os.Getwd=/
Oct 13 00:54:59 Private-1 caddy[13570]: LANG=en_US.UTF-8
Oct 13 00:54:59 Private-1 caddy[13570]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Oct 13 00:54:59 Private-1 caddy[13570]: HOME=/var/lib/caddy
Oct 13 00:54:59 Private-1 caddy[13570]: LOGNAME=caddy
Oct 13 00:54:59 Private-1 caddy[13570]: USER=caddy
Oct 13 00:54:59 Private-1 caddy[13570]: SHELL=/sbin/nologin
Oct 13 00:54:59 Private-1 caddy[13570]: {"level":"info","ts":1602564899.312035,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Oct 13 00:54:59 Private-1 systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Oct 13 00:54:59 Private-1 systemd[1]: Unit caddy.service entered failed state.
Oct 13 00:54:59 Private-1 systemd[1]: caddy.service failed.

caddy启动失败，原因如上！请排查原因！
发生错误，安装中断......

**Comment by proxysu** [comment]
这个上面显示，应该是80端口被占用了。造成启动失败，你是用哪种模式出现的问题？可以试一下最新版，另外一个就是如果出错，再次安装前，最好先执行一次卸载。如果是第一次使用ProxySU，最好是用全新的系统，或者将系统重装一下。

**Comment by proxysu** [comment]
> > 这个版本，增加了查看启动出错的信息显示，
> > https://github.com/proxysu/windows/releases/tag/v2.4.3
> 
> ok.试一下.还有一个问题需要咨询,proxysu中有没有卸载非proxysu脚本安装的ss,ssr,v2ray,Trojan等的功能
> 有些人不想重新系统,直接使用proxysu安装,但是系统又安装了其他脚本,又想卸载之前的脚本.

这个情况，一开始时，也想支持卸载其他脚本的安装的，但是发现实际中很难实现，因为每种脚本安装方式不同，所留下的文件残留也不同，很难完全卸载干净，而且这样做，也可能会引起争议，所以就不能支持了。原来是什么脚本安装的，这个脚本一般都会提供卸载功能，如果有，可以使用原来脚本的卸载功能卸载。
