### ISSUE TITLE
Win10下使用直接闪退

### ISSUE THREAD

**Issue by twzchi** [proxysu/windows#23]
使用的最新版本：v2.3.1
1.VPS 为亚马逊aws 的lightsail
2.使用了密钥登陆
3.设置了管理模式运行

反馈问题：点击安装V2ray，直接 闪退，

**Comment by istek** [comment]
window 10 密钥登陆，直接闪退。

**Comment by twzchi** [comment]
> window 10 密钥登陆，直接闪退。
坐等更新？

**Comment by twzchi** [comment]
已经解决 ，不能使用PUTTY的密钥 不支持
