### ISSUE TITLE
Ubuntu 16.04.7 LTS安装v2ray WS+TLS失败

### ISSUE THREAD

**Issue by zfh135072** [proxysu/windows#24]
ProxySU版本：v2.3.1
安装选项：V2Ray WebSocket+TLS+Web
错误信息如下：

The following packages have unmet dependencies:
 libarchive-tools : Depends: libarchive13 (= 3.2.1-2~ubuntu16.04.1) but 3.1.2-11ubuntu0.16.04.8 is to be installed
error: Installation of libarchive-tools failed, please check your network.

**Comment by proxysu** [comment]
可以切换到Ubuntu18.04或者debian9以上，试试。
