### ISSUE TITLE
申请证书总是失败

### ISSUE THREAD

**Issue by lilong8850** [proxysu/windows#25]
申请域名证书......
/root/.acme.sh/acme.sh  --issue  --standalone  -d yuchan.ml
[Mon Oct  5 17:18:56 UTC 2020] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Oct  5 17:18:56 UTC 2020] Standalone mode.
[Mon Oct  5 17:18:56 UTC 2020] Single domain='yuchan.ml'
[Mon Oct  5 17:18:56 UTC 2020] Getting domain auth token for each domain
[Mon Oct  5 17:18:59 UTC 2020] Getting webroot for domain='yuchan.ml'
[Mon Oct  5 17:18:59 UTC 2020] Verifying: yuchan.ml
[Mon Oct  5 17:18:59 UTC 2020] Standalone mode server
[Mon Oct  5 17:19:04 UTC 2020] Pending
[Mon Oct  5 17:19:07 UTC 2020] Pending
[Mon Oct  5 17:19:10 UTC 2020] Pending

证书申请失败！原因未知，请向开发者提问！

**Comment by proxysu** [comment]
是不是被限制频次了？可以更换一个域名，或者增加变化一个子域名。再申请试试。

**Comment by lilong8850** [comment]
换了三个一级域名，两个二级域名都不可以

**Comment by JongYo128** [comment]
我使用心得域名也是证书申请失败

**Comment by JongYo128** [comment]
[Tue 06 Oct 2020 03:52:04 AM EDT] Standalone mode server

证书申请失败！原因未知，请向开发者提问！

**Comment by Alvin9999** [comment]
重装系统，不要用CentOS7，推荐Debain9

**Comment by Alvin9999** [comment]
最好用全新系统

**Comment by JongYo128** [comment]
所有系统都换过，域名也换过，提交都是失败



---原始邮件---
发件人: "自由上网"<notifications@github.com&gt;
发送时间: 2020年10月7日(周三) 凌晨5:26
收件人: "proxysu/windows"<windows@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"JongYo128"<707455569@qq.com&gt;;
主题: Re: [proxysu/windows] 申请证书总是失败 (#25)




 
最好用全新系统

**Comment by JongYo128** [comment]
我使用10也是失败



---原始邮件---
发件人: "自由上网"<notifications@github.com&gt;
发送时间: 2020年10月7日(周三) 凌晨5:24
收件人: "proxysu/windows"<windows@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"JongYo128"<707455569@qq.com&gt;;
主题: Re: [proxysu/windows] 申请证书总是失败 (#25)




 
重装系统，不要用CentOS7，推荐Debain9

**Comment by proxysu** [comment]
Let's Encrypt 的证书服务器，好像对于申请的主机IP也有限制，如果同一主机IP。在短时间内，过于频繁的申请证书，就会被限制。这个时间，更换任何域名，都不能申请成功。不知你们遇到的是不是这种情况。
还有遇到这种情况，不要马上就频繁再次申请，可以等几分钟或者再长时间。
这是使用的acme.sh脚本遇到的问题。我这边无法给出更具体更有参考价值的回复，可以向其官方项目主页上发问，
https://github.com/acmesh-official/acme.sh

**Comment by proxysu** [comment]
如果是纯IPv6的主机，使用acme.sh申请证书会出现问题。acme.sh是支持ipv6的，ProxySU中没有启用这个功能，这个问题会尽快解决。谢谢反馈

**Comment by proxysu** [comment]
https://github.com/proxysu/windows/releases/tag/v2.4.8
这个版本以上，已经可以支持纯ipv6主机的安装与申请证书。
