### ISSUE TITLE
建议重复安装时允许证书复用

### ISSUE THREAD

**Issue by cx9208** [proxysu/windows#26]
重复安装时申请证书部分会这样
申请域名证书......
/root/.acme.sh/acme.sh  --issue  --standalone  -d xxxx
[Tue Oct  6 17:35:36 MSK 2020] Domains not changed.
[Tue Oct  6 17:35:36 MSK 2020] Skip, Next renewal time is: Sat Dec  5 14:31:14 UTC 2020
[Tue Oct  6 17:35:36 MSK 2020] Add '--force' to force to renew.

证书申请失败！原因未知，请向开发者提问！

**Comment by gswangmd-gssi** [comment]
支持！

**Comment by twzchi** [comment]
那是不行的，这无关软件

**Comment by wangxiaodong1021** [comment]
这是什么原因呢，我也遇到了一样的错误提示。我是刚把域名解析从一个服务器换到另一个服务器了，dns解析是正确的。

**Comment by proxysu** [comment]
你是在使用了卸载功能后，还是遇到了这种情况，是吗？

**Comment by proxysu** [comment]
这个问题，在这一版本应该是解决了，可以试一下。
https://github.com/proxysu/windows/releases/tag/v2.4.3

**Comment by wangxiaodong1021** [comment]
确实解决了👍👍

Xiaodong Wang
________________________________
发件人: proxysu <notifications@github.com>
发送时间: Tuesday, October 13, 2020 9:27:15 AM
收件人: proxysu/windows <windows@noreply.github.com>
抄送: Wang Xiaodong <wangxiaodong1021@gmail.com>; Comment <comment@noreply.github.com>
主题: Re: [proxysu/windows] 建议重复安装时允许证书复用 (#26)


这个问题，在这一版本应该是解决了，可以试一下。
https://github.com/proxysu/windows/releases/tag/v2.4.3
