### ISSUE TITLE
证书申请失败！原因未知，请向开发者提问！

### ISSUE THREAD

**Issue by JongYo128** [proxysu/windows#28]
添加VLESS VMESS XTLS TLS WS 复合方案
Trojan-Go + WebSocket + TLS + Web

CentOS7.5   Debian 9.3/10   Ubuntu18.04

申请域名证书......
/root/.acme.sh/acme.sh  --issue  --standalone  -d mg1.usa1005.tk
[Wed Oct  7 17:05:16 UTC 2020] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Wed Oct  7 17:05:16 UTC 2020] Standalone mode.
[Wed Oct  7 17:05:17 UTC 2020] Create account key ok.
[Wed Oct  7 17:05:17 UTC 2020] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Wed Oct  7 17:05:17 UTC 2020] Registered
[Wed Oct  7 17:05:17 UTC 2020] ACCOUNT_THUMBPRINT='Q6cP3VXpG9yBXiQzLdX1meBo3eINXwxbz2Tk_LyjPwg'
[Wed Oct  7 17:05:17 UTC 2020] Creating domain key
[Wed Oct  7 17:05:17 UTC 2020] The domain key is here: /root/.acme.sh/mg1.usa1005.tk/mg1.usa1005.tk.key
[Wed Oct  7 17:05:17 UTC 2020] Single domain='mg1.usa1005.tk'
[Wed Oct  7 17:05:17 UTC 2020] Getting domain auth token for each domain
[Wed Oct  7 17:05:18 UTC 2020] Getting webroot for domain='mg1.usa1005.tk'
[Wed Oct  7 17:05:18 UTC 2020] Verifying: mg1.usa1005.tk
[Wed Oct  7 17:05:18 UTC 2020] Standalone mode server

证书申请失败！原因未知，请向开发者提问！

**Comment by twzchi** [comment]
换个二级域名~同一顶级域名 不能申请多次

**Comment by JongYo128** [comment]
> 换个二级域名~同一顶级域名 不能申请多次

我新申请的两个域名也是一样只可以使用推荐的v2ray

**Comment by proxysu** [comment]
这是使用的acme.sh脚本遇到的问题。
ProxySU在这个模式中，调用的是acme.sh的脚本申请证书。
很抱歉，我这边无法给出更具体、更有参考价值的回复，可以向其官方项目主页上发问，
https://github.com/acmesh-official/acme.sh
这种情况，我也遇到过，后来我换了一个IP。就没事了。
Let's Encrypt 的证书服务器，好像对于申请的主机IP也有限制，如果同一主机IP。在短时间内，过于频繁的申请证书，就会被限制。这个时间，更换任何域名，都不能申请成功。不知你们遇到的是不是这种情况。
还有遇到这种情况，不要马上就频繁再次申请，可以等几分钟或者再长时间。

**Comment by proxysu** [comment]
如果是纯ipv6使用acme.sh申请证书会出错。请改用caddy申请证书的模式。

**Comment by proxysu** [comment]
acme.sh是支持使用ipv6申请证书的，目前ProxySU中没有启用这个功能，会尽快更新。

**Comment by proxysu** [comment]
添加支持纯IPV6主机，安装过程中，将临时设置NAT64网关。仅用于布署代理，布署完成后，则会删除。注意，纯IPV6 的主机无法直接访问纯IPV4的网络。
https://github.com/proxysu/windows/releases/tag/v2.4.8

**Comment by josephwehbe5** [comment]
It's the firewall on your router(s), just enable all ports temporality for the private IP.
Also, recommend enabling DMZ.

Welcome.
