### ISSUE TITLE
尝试多次安装Caddy失败！

### ISSUE THREAD

**Issue by sunnyadams** [proxysu/windows#29]
证书申请成功！
安装证书到V2ray......
mkdir -p /usr/local/etc/v2ray/ssl

/root/.acme.sh/acme.sh  --installcert  -d vv2.sunnyadam.tk  --certpath /usr/local/etc/v2ray/ssl/v2ray_ssl.crt --keypath /usr/local/etc/v2ray/ssl/v2ray_ssl.key  --capath  /usr/local/etc/v2ray/ssl/v2ray_ssl.crt  --reloadcmd  "systemctl restart v2ray"
[Thu Oct  8 01:29:45 UTC 2020] Installing cert to:/usr/local/etc/v2ray/ssl/v2ray_ssl.crt
[Thu Oct  8 01:29:45 UTC 2020] Installing CA to:/usr/local/etc/v2ray/ssl/v2ray_ssl.crt
[Thu Oct  8 01:29:45 UTC 2020] Installing key to:/usr/local/etc/v2ray/ssl/v2ray_ssl.key
[Thu Oct  8 01:29:45 UTC 2020] Run reload cmd: systemctl restart v2ray
[Thu Oct  8 01:29:45 UTC 2020] Reload success

if [ ! -f "/usr/local/etc/v2ray/ssl/v2ray_ssl.key" ]; then echo "0"; else echo "1"; fi | head -n 1
1

证书成功安装到V2Ray!
chmod 644 /usr/local/etc/v2ray/ssl/v2ray_ssl.key

安装Caddy......
echo "deb [trusted=yes] https://apt.fury.io/caddy/ /" | tee -a /etc/apt/sources.list.d/caddy-fury.list
deb [trusted=yes] https://apt.fury.io/caddy/ /

apt install -y apt-transport-https
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version (1.8.2.1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

apt -qq update
5 packages can be upgraded. Run 'apt list --upgradable' to see them.

apt -y -qq install caddy
caddy is already the newest version (2.2.0).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

find / -name caddy
/usr/share/caddy
/etc/bash_completion.d/caddy
/etc/caddy
/var/lib/caddy
/var/lib/caddy/.config/caddy

安装Caddy失败！

**Comment by proxysu** [comment]
你用的是哪一个版本的linux?

**Comment by one02free** [comment]
我也是最后提示：Caddy启动失败，原因未知！请向开发者问询！

**Comment by sunnyadams** [comment]
> 你用的是哪一个版本的linux?

Debian 10

**Comment by proxysu** [comment]
> > 你用的是哪一个版本的linux?
> 
> Debian 10


我看信息回显中已经显示：
caddy is already the newest version (2.2.0).
但是在程序确认时，却找不到可执行文件。这个可真是很少见。

你可以，用ProxySU自带的卸载功能，执行一遍卸载，再试着安装一下。

**Comment by proxysu** [comment]
> 我也是最后提示：Caddy启动失败，原因未知！请向开发者问询！（搬瓦工的Centos 7 x86_64 bbr 、Centos 8 x86_64 都不行）

如果caddy启动失败可以用以下命令，查看失败的原因:
journalctl --boot -u caddy.service

**Comment by proxysu** [comment]
这个原因找到了，是一个bug。下一个版本中，会修复。

**Comment by proxysu** [comment]
把系统重装后，试试这个版本是否可以？
https://github.com/proxysu/windows/releases/tag/v2.4.3

**Comment by sunnyadams** [comment]
> 把系统重装后，试试这个版本是否可以？
> https://github.com/proxysu/windows/releases/tag/v2.4.3

已近修复了，感谢感谢
