### ISSUE TITLE
trojan无法正常使用

### ISSUE THREAD

**Issue by Alvin9999** [proxysu/windows#3]
用新ip+新域名+最新客户端都无法正常使用。端口正常，伪装域名可以打开。

**Comment by Alvin9999** [comment]
v2ray和naiveproxy正常，就trojan不行，试了几次了

**Comment by Alvin9999** [comment]
原因找到了，vpn默认会开启ipv6，关闭ipv6部署就好了，可以考虑加在软件上哦

**Comment by proxysu** [comment]
好的，谢谢反馈。
