### ISSUE TITLE
caddy添加网页模板

### ISSUE THREAD

**Issue by ITdesk01** [proxysu/windows#30]
HI
你的软件很不错，我用了一下，发现caddy建好以后，访问网页是没有模板的，我觉得可以把网页模板也加进去一下

这是一些静态的网页模板可以套用
1. https://templated.co/intensify
2. https://templated.co/binary
3. https://templated.co/retrospect
4. https://templated.co/spatial
5. https://templated.co/monochromed
6. https://templated.co/transit
7. https://templated.co/interphase
8. https://templated.co/ion
9. https://templated.co/solarize
10. https://templated.co/phaseshift
11. https://templated.co/horizons
12. https://templated.co/grassygrass
13. https://templated.co/breadth
14. https://templated.co/undeviating
15. https://templated.co/lorikeet

**Comment by proxysu** [comment]
好的，谢谢你的建议，后期会增加这个功能。

**Comment by proxysu** [comment]
https://github.com/proxysu/windows/releases/tag/v2.4.16
这个版本，增加了伪装网站功功能，使用Caddy的反向代理。不知道是否可以满足这个需要。如果可以，就不需要增加模板了，因为，增加的模板再多也是有限的，反而会成为特征。

**Comment by ITdesk01** [comment]
> https://github.com/proxysu/windows/releases/tag/v2.4.16
> 这个版本，增加了伪装网站功功能，使用Caddy的反向代理。不知道是否可以满足这个需要。如果可以，就不需要增加模板了，因为，增加的模板再多也是有限的，反而会成为特征。

我觉得没啥问题，确实模板再多也是有针对性的，还不如随机
