### ISSUE TITLE
可否同时安装vless+MTProto？

### ISSUE THREAD

**Issue by wimdaw** [proxysu/windows#32]

**Comment by proxysu** [comment]
你可以vless使用443端口，MTProto使用其他的https端口。比如：2053，2083，2087，2096，8443等。这样就可以在同一台主机上，同时安装vless与MTProto了。

**Comment by wimdaw** [comment]
没法啊，我安装了vless再安装MTproto 还是会检测80和443端口的占用，即使我用的不是这两个端口，我用的2083，依然会检测端口占用然后没法安装

**Comment by proxysu** [comment]
这个bug已经修复。
https://github.com/proxysu/windows/releases/tag/v2.4.2

**Comment by wimdaw** [comment]
![image](https://user-images.githubusercontent.com/29478061/95776240-85ba4f80-0cf6-11eb-92e9-6be0f1b4c758.png)
安装MTproto到最后启动出现这个错误：Error reading JToken from Jsonreader.Path“，line0，position0.      这是出现了什么问题，麻烦修复下，单装也是这个错误，双装也不行

**Comment by proxysu** [comment]
我这里没有复现这个错误，可否把安装过程，中间窗口的提示信息，发到这里。我来查找一下问题原因。

**Comment by proxysu** [comment]
刚才更新了一测试版，你用这个版本，试一下，看能否成功。
https://github.com/proxysu/windows/blob/master/ProxySU/bin/Beta/Beta.zip

**Comment by wimdaw** [comment]
还是没法，提示:正在登录远程主机......
主机登录成功!
检测是否运行在root权限下...
id -u
0

检测结果：OK！
检测系统是否已经安装mtg......
find / -name mtg

检测结果：未安装mtg
检测系统是否符合安装要求......
command -v apt
/usr/bin/apt

command -v dnf

command -v yum

command -v systemctl
/bin/systemctl

command -v getenforce

检测结果：OK!
检测端口占用情况......
lsof -n -P -i :2083 | grep LISTEN

检测结果：未被占用！
开启防火墙相应端口......
uname -m
x86_64

系统环境检测完毕，符合安装要求,开始布署......
正在安装MTProto......
curl -o /tmp/mtg_install.sh https://raw.githubusercontent.com/proxysu/shellscript/master/MTProto/mtg_install.sh

yes | bash /tmp/mtg_install.sh 2083 tg.xiaow.me
[[0;32mInfo[0m] Latest version: [0;32mmtg-linux-amd64v1.0.7[0m

[[0;32mInfo[0m] mtg-linux-amd64 not found, download now...
[[0;32mInfo[0m] mtg-linux-amd64 download completed...

mtg server installed successfully! 
Please execute the command: systemctl enable mtg; systemctl start mtg
Enjoy it!


rm -f /tmp/mtg_install.sh

find / -name mtg
/usr/local/bin/mtg

mtg安装成功！
systemctl enable mtg

正在启动mtg......
systemctl restart mtg

ps aux | grep mtg
root     16496  6.6  8.6 834088 15016 ?        Ssl  00:15   0:00 /usr/local/bin/mtg run --bind=0.0.0.0:2083 eed2e480e6df4f90617ce3889987c3ed6574672e7869616f772e6d65
root     16503  0.0  1.6  11172  2788 ?        Ss   00:15   0:00 bash -c ps aux | grep mtg
root     16505  0.0  0.5  12784   900 ?        S    00:15   0:00 grep mtg

mtg启动成功！
BBR测试......
uname -r
4.14.129-bbrplus

sysctl net.ipv4.tcp_congestion_control | grep bbr
net.ipv4.tcp_congestion_control = bbrplus

BBR已经启用了！
生成客户端配置......
MTProto+TLS安装成功,祝你玩的愉快！！
安装失败!
![QQ截图20201013121537](https://user-images.githubusercontent.com/29478061/95814874-107a6900-0d4e-11eb-8838-9340e85bdc55.jpg)
![QQ截图20201013121545](https://user-images.githubusercontent.com/29478061/95814882-14a68680-0d4e-11eb-9b09-8950fe93cd54.jpg)

**Comment by wimdaw** [comment]
系统是debian9

**Comment by proxysu** [comment]
这是一个bug，你试一下这个版本，应该是修复了。
https://github.com/proxysu/windows/releases/tag/v2.4.14

**Comment by wimdaw** [comment]
没有解决，现在单装MTP都出错，装到最后成功了，好像是读取配置的时候出了问题

**Comment by proxysu** [comment]
你是用的哪家vps商？linux的版本是哪个？
再试一下，这个新版本，
https://github.com/proxysu/windows/releases/tag/v2.4.16
按说是优化了，获取配置文件的过程，不应该再出这种错误才对。

**Comment by proxysu** [comment]
还有整个安装日志，删去ip与域名，发到这里，我排查一下，原因。

**Comment by wimdaw** [comment]
正在登录远程主机......
主机登录成功!
检测是否运行在root权限下...
id -u
0

检测结果：OK！
检测系统是否已经安装mtg......
find / -name mtg

检测结果：未安装mtg
检测系统是否符合安装要求......
command -v apt
/usr/bin/apt

command -v dnf


command -v yum


command -v systemctl
/bin/systemctl

command -v getenforce


检测结果：OK!
apt -qq update
2 packages can be upgraded. Run 'apt list --upgradable' to see them.

apt -y -qq install dnsutils
The following additional packages will be installed:
  bind9-host geoip-database libbind9-140 libdns162 libgeoip1 libicu57
  libisc160 libisccc140 libisccfg140 liblwres141 libxml2 sgml-base xml-core
Suggested packages:
  rblcheck geoip-bin sgml-base-doc debhelper
The following NEW packages will be installed:
  bind9-host dnsutils geoip-database libbind9-140 libdns162 libgeoip1 libicu57
  libisc160 libisccc140 libisccfg140 liblwres141 libxml2 sgml-base xml-core
0 upgraded, 14 newly installed, 0 to remove and 2 not upgraded.
Need to get 13.7 MB of archives.
After this operation, 47.9 MB of additional disk space will be used.
Selecting previously unselected package sgml-base.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 42885 files and directories currently installed.)
Preparing to unpack .../00-sgml-base_1.29_all.deb ...
Unpacking sgml-base (1.29) ...
Selecting previously unselected package libgeoip1:amd64.
Preparing to unpack .../01-libgeoip1_1.6.9-4_amd64.deb ...
Unpacking libgeoip1:amd64 (1.6.9-4) ...
Selecting previously unselected package libicu57:amd64.
Preparing to unpack .../02-libicu57_57.1-6+deb9u4_amd64.deb ...
Unpacking libicu57:amd64 (57.1-6+deb9u4) ...
Selecting previously unselected package libxml2:amd64.
Preparing to unpack .../03-libxml2_2.9.4+dfsg1-2.2+deb9u3_amd64.deb ...
Unpacking libxml2:amd64 (2.9.4+dfsg1-2.2+deb9u3) ...
Selecting previously unselected package libisc160:amd64.
Preparing to unpack .../04-libisc160_1%3a9.10.3.dfsg.P4-12.3+deb9u7_amd64.deb ...
Unpacking libisc160:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Selecting previously unselected package libdns162:amd64.
Preparing to unpack .../05-libdns162_1%3a9.10.3.dfsg.P4-12.3+deb9u7_amd64.deb ...
Unpacking libdns162:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Selecting previously unselected package libisccc140:amd64.
Preparing to unpack .../06-libisccc140_1%3a9.10.3.dfsg.P4-12.3+deb9u7_amd64.deb ...
Unpacking libisccc140:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Selecting previously unselected package libisccfg140:amd64.
Preparing to unpack .../07-libisccfg140_1%3a9.10.3.dfsg.P4-12.3+deb9u7_amd64.deb ...
Unpacking libisccfg140:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Selecting previously unselected package libbind9-140:amd64.
Preparing to unpack .../08-libbind9-140_1%3a9.10.3.dfsg.P4-12.3+deb9u7_amd64.deb ...
Unpacking libbind9-140:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Selecting previously unselected package liblwres141:amd64.
Preparing to unpack .../09-liblwres141_1%3a9.10.3.dfsg.P4-12.3+deb9u7_amd64.deb ...
Unpacking liblwres141:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Selecting previously unselected package bind9-host.
Preparing to unpack .../10-bind9-host_1%3a9.10.3.dfsg.P4-12.3+deb9u7_amd64.deb ...
Unpacking bind9-host (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Selecting previously unselected package dnsutils.
Preparing to unpack .../11-dnsutils_1%3a9.10.3.dfsg.P4-12.3+deb9u7_amd64.deb ...
Unpacking dnsutils (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Selecting previously unselected package geoip-database.
Preparing to unpack .../12-geoip-database_20170512-1_all.deb ...
Unpacking geoip-database (20170512-1) ...
Selecting previously unselected package xml-core.
Preparing to unpack .../13-xml-core_0.17_all.deb ...
Unpacking xml-core (0.17) ...
Setting up geoip-database (20170512-1) ...
Setting up sgml-base (1.29) ...
Setting up libgeoip1:amd64 (1.6.9-4) ...
Setting up libicu57:amd64 (57.1-6+deb9u4) ...
Setting up libxml2:amd64 (2.9.4+dfsg1-2.2+deb9u3) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up liblwres141:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Setting up xml-core (0.17) ...
Setting up libisc160:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Setting up libisccc140:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Setting up libdns162:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Setting up libisccfg140:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Setting up libbind9-140:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Setting up bind9-host (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Setting up dnsutils (1:9.10.3.dfsg.P4-12.3+deb9u7) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Processing triggers for sgml-base (1.29) ...

apt -qq update
2 packages can be upgraded. Run 'apt list --upgradable' to see them.

apt -y -qq install curl
The following additional packages will be installed:
  ca-certificates libcurl3 libldap-2.4-2 libldap-common libnghttp2-14 librtmp1
  libsasl2-2 libsasl2-modules libsasl2-modules-db libssh2-1 openssl
Suggested packages:
  libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal
  libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql
The following NEW packages will be installed:
  ca-certificates curl libcurl3 libldap-2.4-2 libldap-common libnghttp2-14
  librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db libssh2-1 openssl
0 upgraded, 12 newly installed, 0 to remove and 2 not upgraded.
Need to get 2,287 kB of archives.
After this operation, 4,538 kB of additional disk space will be used.
Selecting previously unselected package libsasl2-modules-db:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 43058 files and directories currently installed.)
Preparing to unpack .../00-libsasl2-modules-db_2.1.27~101-g0780600+dfsg-3+deb9u1_amd64.deb ...
Unpacking libsasl2-modules-db:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Selecting previously unselected package libsasl2-2:amd64.
Preparing to unpack .../01-libsasl2-2_2.1.27~101-g0780600+dfsg-3+deb9u1_amd64.deb ...
Unpacking libsasl2-2:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Selecting previously unselected package libldap-common.
Preparing to unpack .../02-libldap-common_2.4.44+dfsg-5+deb9u4_all.deb ...
Unpacking libldap-common (2.4.44+dfsg-5+deb9u4) ...
Selecting previously unselected package libldap-2.4-2:amd64.
Preparing to unpack .../03-libldap-2.4-2_2.4.44+dfsg-5+deb9u4_amd64.deb ...
Unpacking libldap-2.4-2:amd64 (2.4.44+dfsg-5+deb9u4) ...
Selecting previously unselected package openssl.
Preparing to unpack .../04-openssl_1.1.0l-1~deb9u1_amd64.deb ...
Unpacking openssl (1.1.0l-1~deb9u1) ...
Selecting previously unselected package ca-certificates.
Preparing to unpack .../05-ca-certificates_20200601~deb9u1_all.deb ...
Unpacking ca-certificates (20200601~deb9u1) ...
Selecting previously unselected package libnghttp2-14:amd64.
Preparing to unpack .../06-libnghttp2-14_1.18.1-1+deb9u1_amd64.deb ...
Unpacking libnghttp2-14:amd64 (1.18.1-1+deb9u1) ...
Selecting previously unselected package librtmp1:amd64.
Preparing to unpack .../07-librtmp1_2.4+20151223.gitfa8646d.1-1+b1_amd64.deb ...
Unpacking librtmp1:amd64 (2.4+20151223.gitfa8646d.1-1+b1) ...
Selecting previously unselected package libssh2-1:amd64.
Preparing to unpack .../08-libssh2-1_1.7.0-1+deb9u1_amd64.deb ...
Unpacking libssh2-1:amd64 (1.7.0-1+deb9u1) ...
Selecting previously unselected package libcurl3:amd64.
Preparing to unpack .../09-libcurl3_7.52.1-5+deb9u12_amd64.deb ...
Unpacking libcurl3:amd64 (7.52.1-5+deb9u12) ...
Selecting previously unselected package curl.
Preparing to unpack .../10-curl_7.52.1-5+deb9u12_amd64.deb ...
Unpacking curl (7.52.1-5+deb9u12) ...
Selecting previously unselected package libsasl2-modules:amd64.
Preparing to unpack .../11-libsasl2-modules_2.1.27~101-g0780600+dfsg-3+deb9u1_amd64.deb ...
Unpacking libsasl2-modules:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Setting up libnghttp2-14:amd64 (1.18.1-1+deb9u1) ...
Setting up libldap-common (2.4.44+dfsg-5+deb9u4) ...
Setting up libsasl2-modules-db:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Setting up libsasl2-2:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Setting up librtmp1:amd64 (2.4+20151223.gitfa8646d.1-1+b1) ...
Setting up libssh2-1:amd64 (1.7.0-1+deb9u1) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up libldap-2.4-2:amd64 (2.4.44+dfsg-5+deb9u4) ...
Setting up openssl (1.1.0l-1~deb9u1) ...
Setting up libsasl2-modules:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Setting up ca-certificates (20200601~deb9u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Updating certificates in /etc/ssl/certs...
126 added, 0 removed; done.
Setting up libcurl3:amd64 (7.52.1-5+deb9u12) ...
Setting up curl (7.52.1-5+deb9u12) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Processing triggers for ca-certificates (20200601~deb9u1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

apt -y -qq install unzip
Suggested packages:
  zip
The following NEW packages will be installed:
  unzip
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 172 kB of archives.
After this operation, 559 kB of additional disk space will be used.
Selecting previously unselected package unzip.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 43457 files and directories currently installed.)
Preparing to unpack .../unzip_6.0-21+deb9u2_amd64.deb ...
Unpacking unzip (6.0-21+deb9u2) ...
Setting up unzip (6.0-21+deb9u2) ...

apt -y -qq install xz-utils
The following NEW packages will be installed:
  xz-utils
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 266 kB of archives.
After this operation, 528 kB of additional disk space will be used.
Selecting previously unselected package xz-utils.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 43475 files and directories currently installed.)
Preparing to unpack .../xz-utils_5.2.2-1.2+b1_amd64.deb ...
Unpacking xz-utils (5.2.2-1.2+b1) ...
Setting up xz-utils (5.2.2-1.2+b1) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode

apt -y -qq install lsof
Suggested packages:
  perl
The following NEW packages will be installed:
  lsof
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 313 kB of archives.
After this operation, 451 kB of additional disk space will be used.
Selecting previously unselected package lsof.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 43521 files and directories currently installed.)
Preparing to unpack .../lsof_4.89+dfsg-0.1_amd64.deb ...
Unpacking lsof (4.89+dfsg-0.1) ...
Setting up lsof (4.89+dfsg-0.1) ...

正在检测是否为纯ipv6主机......
curl -s https://api.ip.sb/ip --ipv4
xx.xxx.xx.xxx

curl -s https://api.ip.sb/ip --ipv6
xxxx:xxxx::xx

检测端口占用情况......
lsof -n -P -i :8443 | grep LISTEN


检测结果：未被占用！
开启防火墙相应端口......
uname -m
x86_64

系统环境检测完毕，符合安装要求,开始布署......
正在安装MTProto......
curl -o /tmp/mtg_install.sh https://raw.githubusercontent.com/proxysu/shellscript/master/MTProto/mtg_install.sh

yes | bash /tmp/mtg_install.sh 8443 tg.xiaow.me
[[0;32mInfo[0m] Latest version: [0;32mmtg-linux-amd64v1.0.7[0m

[[0;32mInfo[0m] mtg-linux-amd64 not found, download now...
[[0;32mInfo[0m] mtg-linux-amd64 download completed...

mtg server installed successfully! 
Please execute the command: systemctl enable mtg; systemctl start mtg
Enjoy it!


rm -f /tmp/mtg_install.sh

find / -name mtg
/usr/local/bin/mtg

mtg安装成功！
systemctl enable mtg

正在启动mtg......
systemctl restart mtg

ps aux | grep mtg
root      4039  4.2  9.0 834088 15660 ?        Ssl  00:55   0:00 /usr/local/bin/mtg run --bind=0.0.0.0:8443 ee8c9c8b4918a35f743cc30ea7fa9a575474672e7869616f772e6d65
root      4048  0.0  1.6  11172  2860 ?        Ss   00:55   0:00 bash -c ps aux | grep mtg
root      4050  0.0  0.5  12784   948 ?        S    00:55   0:00 grep mtg

mtg启动成功！
BBR测试......
uname -r
4.14.129-bbrplus

sysctl net.ipv4.tcp_congestion_control | grep bbr
net.ipv4.tcp_congestion_control = bbrplus

BBR已经启用了！
生成客户端配置......
cat /usr/local/etc/mtg_info.json
cat: /usr/local/etc/mtg_info.json: No such file or directory


MTProto+TLS安装成功,祝你玩的愉快！！
安装失败!

![QQ截图20201030125943](https://user-images.githubusercontent.com/29478061/97661680-037caa00-1ab0-11eb-98b4-05391dd2cc1a.jpg)
厂商是sentris 系统是debian9

**Comment by proxysu** [comment]
https://github.com/proxysu/windows/raw/master/ProxySU/bin/Beta/Beta.zip
这是一个新的测试版，你下载试一下，看是否还会出现这种错误。这一测试版，优化了一下配置文件生成流程。

**Comment by wimdaw** [comment]
正在登录远程主机......
主机登录成功!
检测是否运行在root权限下...
id -u
0

检测结果：OK！
检测系统是否已经安装mtg......
if [[ -f /usr/local/bin/mtg ]];then echo '1';else echo '0'; fi
0

检测结果：未安装mtg
检测系统是否符合安装要求......
command -v apt
/usr/bin/apt

command -v dnf


command -v yum


command -v systemctl
/bin/systemctl

command -v getenforce


检测结果：OK!
apt update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://httpredir.debian.org/debian stretch InRelease
Hit:3 http://httpredir.debian.org/debian stretch-updates InRelease
Hit:4 http://httpredir.debian.org/debian stretch Release
Ign:6 https://apt.fury.io/caddy  InRelease
Ign:7 https://apt.fury.io/caddy  Release
Ign:8 https://apt.fury.io/caddy  Packages
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:10 https://apt.fury.io/caddy  Translation-en
Hit:8 https://apt.fury.io/caddy  Packages
Ign:8 https://apt.fury.io/caddy  Packages
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:10 https://apt.fury.io/caddy  Translation-en
Ign:8 https://apt.fury.io/caddy  Packages
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:10 https://apt.fury.io/caddy  Translation-en
Hit:8 https://apt.fury.io/caddy  Packages
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:10 https://apt.fury.io/caddy  Translation-en
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:10 https://apt.fury.io/caddy  Translation-en
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:10 https://apt.fury.io/caddy  Translation-en
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.

apt -y install xz-utils
Reading package lists...
Building dependency tree...
Reading state information...
xz-utils is already the newest version (5.2.2-1.2+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

正在检测是否为纯ipv6主机......
curl -s https://api.ip.sb/ip --ipv4
xx.xxx.xx.xxx

curl -s https://api.ip.sb/ip --ipv6
xxxx:xxxx::xx

检测端口占用情况......
lsof -n -P -i :8443 | grep LISTEN


检测结果：未被占用！
开启防火墙相应端口......
uname -m
x86_64

系统环境检测完毕，符合安装要求,开始布署......
正在安装MTProto......
curl -o /tmp/mtg_install.sh https://raw.githubusercontent.com/proxysu/shellscript/master/MTProto/mtg_install.sh

if [[ -f /tmp/installproxy.sh ]];then echo '1';else echo '0'; fi
0

文件下载失败！
发生错误，安装中断......

**Comment by wimdaw** [comment]
这个版本文件都下载不起了

**Comment by proxysu** [comment]
看到了，这是一个bug，优化代码时，出现了一个错误，这一测试版，修复了这一个错误。
https://github.com/proxysu/windows/raw/master/ProxySU/bin/Beta/Beta.zip

**Comment by wimdaw** [comment]
感谢，已成功，就是生成配置的时候还是ip连接，不是域名加端口连接，冒昧的问一句，可以加cdn嘛

**Comment by proxysu** [comment]
这个MTProto是不支持cdn的，如果你想使用域名，可以将域名解析到该ip，并用域名代替该ip。但是还是不能使用cdn。
