### ISSUE TITLE
资源工具显示不正常

### ISSUE THREAD

**Issue by cncherisher** [proxysu/windows#33]
OS：win10LTSC
![图片](https://user-images.githubusercontent.com/46522179/95653817-04b05c00-0b2e-11eb-86a0-629310216de5.png)
![图片](https://user-images.githubusercontent.com/46522179/95653823-11cd4b00-0b2e-11eb-9418-7328ea232b29.png)
点击前进后退会报错
![图片](https://user-images.githubusercontent.com/46522179/95653832-23aeee00-0b2e-11eb-97fc-6a9844f5427f.png)

**Comment by proxysu** [comment]
这个表示已经没有可以前进的页面了。这里应该算是一个bug。不过，也没什么打紧的。主要是c#内置的浏览器组件，只能使用IE内核。硬伤。无解。

**Comment by cncherisher** [comment]
可以在软件里面贴一个超链接指向这个页面，让用户用默认浏览器打开
