### ISSUE TITLE
端口参数输入框不支持粘贴操作

### ISSUE THREAD

**Issue by hexiyou** [proxysu/windows#34]
![image](https://user-images.githubusercontent.com/1593944/95683910-9ac4af00-0c20-11eb-95ad-8f9ede9c97ee.png)
如题，端口参数输入框不支持粘贴操作，另外两个主机和用户输入框则可以Ctrl+V粘贴，把端口文本框粘贴权限放开一下？

**Comment by proxysu** [comment]
下一个版本会放开权限。

**Comment by proxysu** [comment]
版本已更新，开放端口框粘贴功能
https://github.com/proxysu/windows/releases/tag/v2.4.3
