### ISSUE TITLE
debian10 安装trojan-go后报错，permission denied

### ISSUE THREAD

**Issue by betaback** [proxysu/windows#4]
如题，安装完trojan-go之后发现无法使用，登录vps查看错误日志，如下
trojan-go.service: Failed to execute command: Permission denied
trojan-go.service: Failed at step EXEC spawning /usr/bin/trojan-go: Permission denied

**Comment by proxysu** [comment]
看这个提示，似乎是权限问题，我排查一下。

**Comment by Alvin9999** [comment]
@proxysu  搭建了很多次的trojan-go，都不行，可能是脚本的问题。您可以参考下下面这个脚本，实测没问题。如下：
https://github.com/jinwyp/one_click_script

**Comment by Alvin9999** [comment]
@proxysu 补充一下，搭建trojan-go的时候很顺利，最后都能生成配置文件，但就是用不了。

**Comment by betaback** [comment]
发现有权限问题后 用chmod命令手动设置了权限也不可以

**Comment by Alvin9999** [comment]
@betaback 用debian9看看

**Comment by proxysu** [comment]
这是旧脚本中，生成的trojan-go.service中的用户权限问题，在ProxySU v1.8.1以后已修复。

**Comment by Alvin9999** [comment]
> 这是旧脚本中，生成的trojan-go.service中的用户权限问题，在ProxySU v1.8.1以后已修复。

看到更新了，感谢。

**Comment by Alvin9999** [comment]
@proxysu 最新版里面没有伪装网站的设置选项了。

**Comment by Alvin9999** [comment]
用CentOS7系统测试了naiveproxy和trojan-go，能生产配置文件，但都无法正常使用代理。但用单独的脚本就可以。v2ray还没测试。

**Comment by Alvin9999** [comment]
v2ray也测试了，ws+tls+caddy也不行

**Comment by proxysu** [comment]
> @proxysu 最新版里面没有伪装网站的设置选项了。

暂时去掉了，主要是对Caddy2配置还不熟悉，设置了一下，不成功，就暂时先去掉了，等有时间，再好好研究一下Caddy2的配置。

**Comment by proxysu** [comment]
> 用CentOS7系统测试了naiveproxy和trojan-go，能生产配置文件，但都无法正常使用代理。但用单独的脚本就可以。v2ray还没测试。



> v2ray也测试了，ws+tls+caddy也不行

这两个问题，已经找到原因，是在CentOS7的安装过程出现交互，没有做预先的处理，ProxySU v1.8.2已修复，非常感谢您的测试。

**Comment by Alvin9999** [comment]
> > 用CentOS7系统测试了naiveproxy和trojan-go，能生产配置文件，但都无法正常使用代理。但用单独的脚本就可以。v2ray还没测试。
> 
> > v2ray也测试了，ws+tls+caddy也不行
> 
> 这两个问题，已经找到原因，是在CentOS7的安装过程出现交互，没有做预先的处理，ProxySU v1.8.2已修复，非常感谢您的测试。

初步测试了下1.8.2版本，v2ray还是不行。Naiveproxy一直卡在“正在升级服务端”那里（2次）。trojan-go还没测试。请问你开发测试的时候vps选的什么系统呢？

**Comment by proxysu** [comment]
一般是在Debian9下测试的，vultr。
我在vultr的CentOS7下测试通过。不知道，你用的是哪个VPS商的？
如果Naiveproxy一直卡在“正在升级服务端”，应该是下载带插件的caddy文件出问题了。
在程序源码中第3595行：
 client.RunCommand(@"curl -o /tmp/caddy.zip https://raw.githubusercontent.com/proxysu/Resources/master/Caddy2/caddy20200816.zip");
                    client.RunCommand(@"unzip /tmp/caddy.zip"); //解压到当前目录 ~/
                    client.RunCommand(@"chmod +x caddy");
                    client.RunCommand(@"systemctl stop caddy;rm -f /usr/bin/caddy");
                    client.RunCommand(@"cp ./caddy /usr/bin/");
双引号中都是执行的shell命令。你可以手动试一下，看问题出在哪里。

**Comment by proxysu** [comment]
ssr套上tls后，速度并不比v2ray更好。你说的这种方案，有没有相关资料？比如服务端的搭建，还有客户端如何设置？

**Comment by Alvin9999** [comment]
> ssr套上tls后，速度并不比v2ray更好。你说的这种方案，有没有相关资料？比如服务端的搭建，还有客户端如何设置？

有。速度确实不一定比v2ray好。多一种选择吧。如果ss/ssr真正被特征识别了的话，现在肯定灭绝了，然而现在ss/ssr用的人还特别多。从这个项目的点赞可以看出还比较稳定https://github.com/shadowsocks/shadowsocks-windows 

ssr+tls+caddy+bbr一键搭建：https://jeanniestudio.top/2020/03/05/%E6%97%A0%E6%95%8C%E4%BA%86%EF%BC%81ssr-tls-caddy-bbr%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA/

https://jeanniestudio.top/2020/02/26/ssr+tls+caddy%E4%BB%8D%E7%84%B6%E7%A8%B3%E5%BE%97%E4%B8%80%E6%89%B9/

上面这个两个地址还是用的caddy1，故失效，可以参考下。

**Comment by Alvin9999** [comment]
@proxysu ubuntu18搭建trojan-go可行，CentOS7还是不行。

**Comment by Alvin9999** [comment]
防火墙这些都是关闭的

**Comment by proxysu** [comment]
你是用哪家的VPS商？

**Comment by Alvin9999** [comment]
changeip

**Comment by proxysu** [comment]
如果你方便可以加一下，反馈问题的电报群。有问题可以及时反馈。我现在去测试这家的vps。

**Comment by Alvin9999** [comment]
@proxysu   让你破费了，不过我不用电报哦，以后可能会考虑下

**Comment by proxysu** [comment]
定购changeip的vps遇到麻烦，总是被砍单。

**Comment by Alvin9999** [comment]
@proxysu  你先不要买了，谢谢了。等我空了，我重装系统再试试看，也许是装太多的缘故。如果vultr可行，按理说其它应该也可以。

**Comment by Alvin9999** [comment]
@proxysu 重装了系统，换了Debian 9 64bit，naiveproxy可用。

**Comment by Alvin9999** [comment]
换了vps厂商，没有在继续折腾原来的

**Comment by proxysu** [comment]
现在ProxySU可以显示整个安装过程，以及命令执行的结果。如果再遇到问题，可以将安装过程的回显信息，复制出来，去除掉ip,域名等信息，发到这里，我就可以快速定位问题原因。

**Comment by Alvin9999** [comment]
好

**Comment by Alvin9999** [comment]
用centos7系统又测试了下，新系统，分别安装了naiveproxy和trojan-go，安装过程中界面没有任何错误，一直很顺利直到结束，但是根据生产的配置信息无法正常用。很是奇怪。

**Comment by proxysu** [comment]
是的，这是安装脚本的问题，这两天一直在调试，马上会有一个新版本。

**Comment by Alvin9999** [comment]
> 是的，这是安装脚本的问题，这两天一直在调试，马上会有一个新版本。

好的

**Comment by Alvin9999** [comment]
ubuntu 18也遇到了这个问题，安装Trojan-go没有任何报错，但配置信息无法正常使用，应该是服务没有通。

**Comment by proxysu** [comment]
我在vultr的主机上，Ubuntu 18安装Trojan-go测试通过。你可以把安装过程中，显示出的信息，去掉域名IP信息，发在这里，我排查一下。
用最新版本的ProxySU试试。

**Comment by Alvin9999** [comment]
反馈：最新客户端版本,CentOS系统安装naiveproxy正常，可使用。

**Comment by Alvin9999** [comment]
刚看了下，又更新了2个版本，更新速度好快，我用的是1.8.5版本。
请问ssr+tls+caddy有没有在未来的计划中哦？

**Comment by Alvin9999** [comment]
安装trojan-go有一个bug，关于域名申请证书，如果之前申请成功过，当软件失效需要重装时，域名就会一直申请不成功，此时必须更换域名才行。本来准备复制代码发给你，但软件在最后的时候老是崩溃。

**Comment by proxysu** [comment]
> 刚看了下，又更新了2个版本，更新速度好快，我用的是1.8.5版本。
> 请问ssr+tls+caddy有没有在未来的计划中哦？

这个要向后拖一拖了，最近事情有点忙。等忙完这一阵，再添加这个。

**Comment by proxysu** [comment]
> 安装trojan-go有一个bug，关于域名申请证书，如果之前申请成功过，当软件失效需要重装时，域名就会一直申请不成功，此时必须更换域名才行。本来准备复制代码发给你，但软件在最后的时候老是崩溃。

你可以先把系统重装一下。这样会比较好，现在还没有检测和排除旧的安装软件的功能。现在都是假设在全新的系统中安装。

**Comment by Alvin9999** [comment]
@proxysu 好，谢谢

**Comment by proxysu** [comment]
> @proxysu 谢谢提醒。我有一个建议，能否增加一下ssr+tls+caddy的搭建呢？现在用ssr的人还是有很多。

ProxySU-v2.1.0添加了一键安装ssr+tls+caddy。
https://github.com/proxysu/windows/releases/tag/v2.1.0

**Comment by Alvin9999** [comment]
> > @proxysu 谢谢提醒。我有一个建议，能否增加一下ssr+tls+caddy的搭建呢？现在用ssr的人还是有很多。
> 
> ProxySU-v2.1.0添加了一键安装ssr+tls+caddy。
> https://github.com/proxysu/windows/releases/tag/v2.1.0

收到

**Comment by Alvin9999** [comment]
@proxysu 请问加上caddy后，是不是就可以套CDN了？

**Comment by proxysu** [comment]
不能，SSR没有可以支持CDN的协议。V2Ray的众多协议中，也只有WebSocket协议，能完美支持所有CDN。http2协议，也有部分CDN不支持，比如CloudFlare就不支持完整的http2协议。Trojan-go的Websocket模式，也支持所有的CDN。

**Comment by proxysu** [comment]
> @proxysu 请问加上caddy后，是不是就可以套CDN了？

我发现SS使用v2ray-plugin后，可以让SS也支持CDN。就是不知道现在还有多少人在使用SS。现在正在着手添加SS及其各种插件的一键安装。你有什么好的建议没有？

**Comment by proxysu** [comment]
SS的插件simple-obfs也实现了与SSR相同的流量混淆功能。我在实验中，SS+simple-obfs也成功配置了与SSR+TLS+Caddy相同的使用效果。而SS配合其他各种插件（v2ray-plugin、kcptun-plugin、GoQuiet、Cloak），可以实现更多模式。

**Comment by Alvin9999** [comment]
> > @proxysu 请问加上caddy后，是不是就可以套CDN了？
> 
> 我发现SS使用v2ray-plugin后，可以让SS也支持CDN。就是不知道现在还有多少人在使用SS。现在正在着手添加SS及其各种插件的一键安装。你有什么好的建议没有？

现在用SS的人还是有很多，具体多少就不清楚了

**Comment by Alvin9999** [comment]
> SS的插件simple-obfs也实现了与SSR相同的流量混淆功能。我在实验中，SS+simple-obfs也成功配置了与SSR+TLS+Caddy相同的使用效果。而SS配合其他各种插件（v2ray-plugin、kcptun-plugin、GoQuiet、Cloak），可以实现更多模式。

kcptun这个插件可以解决晚高峰断流的问题。
