### ISSUE TITLE
New Issues

### ISSUE THREAD

**Issue by johnzhao0520** [proxysu/windows#40]
![image](https://user-images.githubusercontent.com/53855416/96805391-24a42180-1444-11eb-837c-37a8d001e4e4.png)
未能找到以下路径，安装都不了

**Comment by proxysu** [comment]
这个问题以前有人遇到过。似乎是下载后重命名了文件夹。后来是本地电脑重新启动，把先来下载的ProxySU全部删除，重新下载后，就可以 了，可以试一下，看是否能解决问题。

**Comment by johnzhao0520** [comment]
我重新下载额一个版本放到C盘也可以了


proxysu <notifications@github.com> 于2020年10月22日周四 上午9:09写道：

**Comment by proxysu** [comment]
https://github.com/proxysu/windows/raw/master/ProxySU/bin/Beta/Beta.zip
这是一个针对这个问题进行强化处理的测试版，你可以试一下，看看是否还会出现这种问题。

**Comment by johnzhao0520** [comment]
这个测试版本也可以


proxysu <notifications@github.com> 于2020年10月22日周四 上午10:06写道：
