### ISSUE TITLE
dalao，可不可以增加VLESS的mKCP，垃圾小鸡和垃圾设备也许只有这样能拯救..............

### ISSUE THREAD

**Issue by kokorobeats** [proxysu/windows#43]
dalao，可不可以增加VLESS的mKCP，垃圾小鸡和垃圾设备也许只有这样能拯救..............T^T

**Comment by proxysu** [comment]
可以，这个我抽时间添加一下，现在是业余时间严重不够用啊

**Comment by OleStore** [comment]
确实，垃圾小鸡只能通过mkcp，不然没法愉快的玩耍了

**Comment by proxysu** [comment]
https://github.com/proxysu/windows/releases/tag/v2.4.15
这个版本已增加。

**Comment by OleStore** [comment]
> https://github.com/proxysu/windows/releases/tag/v2.4.15
> 这个版本已增加。

大佬效率真高

**Comment by kokorobeats** [comment]
谢谢dalao！！小鸡有救了！！！
