### ISSUE TITLE
ipv6主机无法安装

### ISSUE THREAD

**Issue by lszhwxa** [proxysu/windows#48]
解析正确！OK!
系统环境检测完毕，符合安装要求,开始布署......
正在安装V2Ray......
curl -o /tmp/go.sh https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Network is unreachable

yes | bash /tmp/go.sh -f
error: Failed to get release list, please check your network.

rm -f /tmp/go.sh

find / -name v2ray
/tmp/v2ray
/usr/local/etc/v2ray

安装失败,脚本运行出错！
发生错误，安装中断......

**Comment by proxysu** [comment]
纯ipv6主机，需要设置NAT64网关才能使用github上的脚本资源，但是ProxySU在安装过程中，如果检测到主机是纯IPV6主机，会自动尝试设置NAT64网关。但是有一点，如果该主机无法使用设置的NAT64网关。就会出现上述情况。出现这种情况，比较麻烦，只能自己手动设置了。

**Comment by proxysu** [comment]
试试这个版本，看是否可以正常安装，这一版本优化了Nat64的选择机制，会自动查找Nat64网关库中可以连通，并且是速度最快的Nat64网关地址。
https://github.com/proxysu/windows/releases/tag/v2.4.14

**Comment by yjwqf** [comment]
最新版也连接不上

**Comment by proxysu** [comment]
安装日志有吗？

**Comment by yjwqf** [comment]
保存的日志只有一句。提示是：连接方没有正确回复或主机没有反应。
----- 原始邮件 -----
发件人：proxysu <notifications@github.com>
收件人：proxysu/windows <windows@noreply.github.com>
抄送人：yjwqf <yjwqf@sina.com>,  Comment <comment@noreply.github.com>
主题：Re:_[proxysu/windows]_ipv6主机无法安装_(#48)
日期：2020年10月28日 12点33分



安装日志有吗？



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
正在登录远程主机......
安装失败!

**Comment by proxysu** [comment]
线路不通。你试试其他shell客户端，是否可以连接吗？

**Comment by proxysu** [comment]
ProxySU使用ssh.net库进行ssh登录，如果是这样的话，你试着加一个代理，看看，也可能存在ssh.net库不兼容的情况，再不行的话，就只能放弃使用ProxySU了，使用其他的一键脚本吧。
也可以先排查一下，连接端口等。按说这种出错的可能性很小。

**Comment by proxysu** [comment]
如果还是不行的话，就用其他shell客户端登录，可以试试下面一位网友分享的脚本：

curl -fsSL https://raw.githubusercontent.com/phlinhng/v2ray-tcp-tls-web/vless/src/v2gun.sh -o ~/v2gun.sh && bash ~/v2gun.sh  

可一键安装VLESS / VMess / Trojan-Go/Naive
支持ipv6主机，如果是纯ipv6主机，需要先设置DNS64/NAT64.root账户设置方法：
echo -e "nameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6" > /etc/resolv.conf
也支持具有sudo权限的非root账户使用。网关设置方法：
echo -e "nameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6"  | sudo tee  /etc/resolv.conf
