### ISSUE TITLE
VLESS+TCP+XTLS+Web 模式安装后，开启CDN无法使用

### ISSUE THREAD

**Issue by huhc702** [proxysu/windows#49]
域名是腾讯云的，DNS改到了Cloudflare解析，证书也是Cloudflare的。安装时不能开启CDN ，安装好之后使用V2rayN，正常使用；回到Cloudflare，开启CDN后，无法正常使用了，测速提示【远程服务器返回错误：（503）服务器不可用】。

**Comment by proxysu** [comment]
这个模式是不支持使用CDN的。因为使用Cloudflare的CDN，目前只能使用websocket协议，XTLS不支持websocket协议。
这个在其官方说明中已说明：
https://www.v2fly.org/config/protocols/vless.html#xtls-%E9%BB%91%E7%A7%91%E6%8A%80

**Comment by huhc702** [comment]
非常感谢，这是我的疏忽
