### ISSUE TITLE
ipv6搭建出现错误

### ISSUE THREAD

**Issue by sduwfc** [proxysu/windows#52]
debian10,安装v2ray的ws+tls,是纯ipv6小鸡,lxc架构.
错误日志:
find / -name v2ray
find: ‘/dev/.lxd-mounts’: Permission denied
find: ‘/sys/kernel/debug’: Permission denied
find: ‘/sys/dev/block’: Permission denied
find: ‘/sys/fs/pstore’: Permission denied
find: ‘/sys/fs/fuse/connections/47’: Permission denied
find: ‘/proc/tty/driver’: Permission denied

**Comment by proxysu** [comment]
https://github.com/proxysu/windows/raw/master/ProxySU/bin/Beta/Beta.zip
这是一个最新的测试版，看看是否解决这个问题。这一版，对ipv6做了专门的优化。

**Comment by sduwfc** [comment]
> https://github.com/proxysu/windows/raw/master/ProxySU/bin/Beta/Beta.zip
> 这是一个最新的测试版，看看是否解决这个问题。这一版，对ipv6做了专门的优化。

这个可以用,非常感谢作者
