### ISSUE TITLE
最新版本部署时闪退

### ISSUE THREAD

**Issue by molun** [proxysu/windows#53]
![image](https://user-images.githubusercontent.com/23138506/97774213-f5eb2100-1b90-11eb-9c00-e9e3dae4718b.png)

**Comment by proxysu** [comment]
方便的话，能否提供以下详细信息？
1。运行ProxySU所使用的windows版本。
2。vps所用linux版本
3。安装选择的代理模式
4。如果可以，请将所用主机所在的服务商也说明一下

**Comment by HaHaIsMe** [comment]
是有闪退的问题！
我的环境：
1）Windows 10 1909
2）CentOS 7 x64
3)   SSR
4)   Vultr
感恩……拜谢……！！

**Comment by proxysu** [comment]
是密码登录，还是密钥登录？

**Comment by proxysu** [comment]
测试过了，没有复现上述错误。你可以切换一下linux的版本，比如debian 9\10等。试一下。

**Comment by proxysu** [comment]
还有一种情况，多个网友反馈过，就是windows系统是精简版，或者一键ghost版，少某些运行库，造成闪退。
解决方法是用原版安装盘，重新装一下系统，就好了，或者用虚拟机安装一个临时用的原版系统也可以。

**Comment by proxysu** [comment]
如果是密钥登录，有可能是密钥格式的问题。下面文档说明了支持的密钥格式。
https://github.com/proxysu/windows/wiki/CommonError

**Comment by molun** [comment]
Windows版本如下：
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2019/‎12/‎15 ‎星期日
操作系统版本	19042.610
体验	Windows Feature Experience Pack 120.2212.31.0

服务器为Google云

软件新老版本都试过，情况一样！采用密钥登录闪退。Putty和FinalShell使用密钥可以正常登录

**Comment by molun** [comment]
密钥原来就是使用puttygen生成的

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/97833560-9ca9fb80-1d10-11eb-8625-e1d9a3b97190.png)

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/97834928-f3650480-1d13-11eb-94f4-6cee2a79b23e.png)
新生成的密钥也不可以，载入密钥进行转换后可以使用了！

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/97835010-227b7600-1d14-11eb-92e8-6443115e4813.png)
三个可以同时点选？不能取消

**Comment by molun** [comment]
Nov 02 06:53:56 hk caddy[23808]: [ERROR] failed to copy buffer:  read tcp 127.0.0.1:57098->127.0.0.1:35532: use of closed network connection
Nov 02 06:54:04 hk caddy[23808]: [ERROR] failed to copy buffer:  read tcp 127.0.0.1:57108->127.0.0.1:35532: use of closed network connection
Nov 02 06:54:10 hk caddy[23808]: [ERROR] failed to copy buffer:  readfrom tcp 127.0.0.1:57714->127.0.0.1:35532: read tcp 10.170.0.25:443->171.120.2.216:51250: use of closed network

**Comment by proxysu** [comment]
> ![image](https://user-images.githubusercontent.com/23138506/97835010-227b7600-1d14-11eb-92e8-6443115e4813.png)
> 三个可以同时点选？不能取消

好的，谢谢反馈，这应该是一个bug.

**Comment by proxysu** [comment]
https://github.com/proxysu/windows/raw/master/ProxySU/bin/Beta/Beta.zip
这是一个测试版，修正了上述错误。
