### ISSUE TITLE
caddy启动失败，原因如上！请排查原因！

### ISSUE THREAD

**Issue by molun** [proxysu/windows#55]
之前安装过233脚本可以正常使用，卸载后用您的软件一键部署出错
![image](https://user-images.githubusercontent.com/23138506/97840361-ce29c380-1d1e-11eb-8cdc-89838087dc78.png)

![image](https://user-images.githubusercontent.com/23138506/97840239-a20e4280-1d1e-11eb-9cff-dac830e0193f.png)
安装Caddy......
echo "deb [trusted=yes] https://apt.fury.io/caddy/ /" | tee -a /etc/apt/sources.list.d/caddy-fury.list
deb [trusted=yes] https://apt.fury.io/caddy/ /

apt install -y apt-transport-https

apt update
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch-backports InRelease
Hit:5 http://deb.debian.org/debian stretch Release
Hit:6 http://packages.cloud.google.com/apt cloud-sdk-stretch InRelease
Hit:7 http://packages.cloud.google.com/apt google-compute-engine-stretch-stable InRelease
Hit:8 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease
Ign:10 https://apt.fury.io/caddy  InRelease
Ign:11 https://apt.fury.io/caddy  Release
Ign:12 https://apt.fury.io/caddy  Packages
Ign:13 https://apt.fury.io/caddy  Translation-en
Ign:14 https://apt.fury.io/caddy  Translation-en_US
Hit:12 https://apt.fury.io/caddy  Packages
Ign:12 https://apt.fury.io/caddy  Packages
Ign:13 https://apt.fury.io/caddy  Translation-en
Ign:14 https://apt.fury.io/caddy  Translation-en_US
Ign:12 https://apt.fury.io/caddy  Packages
Ign:13 https://apt.fury.io/caddy  Translation-en
Ign:14 https://apt.fury.io/caddy  Translation-en_US
Hit:12 https://apt.fury.io/caddy  Packages
Ign:13 https://apt.fury.io/caddy  Translation-en
Ign:14 https://apt.fury.io/caddy  Translation-en_US
Ign:13 https://apt.fury.io/caddy  Translation-en
Ign:14 https://apt.fury.io/caddy  Translation-en_US
Ign:13 https://apt.fury.io/caddy  Translation-en
Ign:14 https://apt.fury.io/caddy  Translation-en_US
Reading package lists...
Building dependency tree...
Reading state information...
13 packages can be upgraded. Run 'apt list --upgradable' to see them.

apt -y install caddy

if [[ -f /usr/bin/caddy ]];then echo '1';else echo '0'; fi
1

Caddy安装成功！
systemctl enable caddy
Failed to enable unit: File caddy.service: No such file or directory

上传Caddy配置文件......
mv /etc/caddy/Caddyfile /etc/caddy/Caddyfile.bak
mv: cannot stat '/etc/caddy/Caddyfile': No such file or directory

sed -i 's/8800/18669/' /etc/caddy/Caddyfile

sed -i 's/##domain##/openwallwrt.gq/g' /etc/caddy/Caddyfile

sed -i 's/##path##/\/vmessws/' /etc/caddy/Caddyfile

sed -i 's/##reverse_Proxy1##/reverse_proxy http:\/\/molun.cf {/ ' /etc/caddy/Caddyfile

sed -i 's/##reverse_Proxy2##/header_up Host molun.cf/' /etc/caddy/Caddyfile

sed -i 's/##reverse_Proxy3##/}/' /etc/caddy/Caddyfile

Caddy配置文件上传成功,OK!
正在启动caddy......
systemctl restart caddy

ps aux | grep caddy
root      4131  0.0  0.4  11176  2916 ?        Ss   07:16   0:00 bash -c ps aux | grep caddy
root      4133  0.0  0.1  12780   956 ?        S    07:16   0:00 grep caddy

caddy启动失败！
正在第二次尝试启动caddy
systemctl restart caddy

ps aux | grep caddy
root      4135  0.0  0.4  11176  2916 ?        Ss   07:16   0:00 bash -c ps aux | grep caddy
root      4137  0.0  0.1  12780   932 ?        S    07:16   0:00 grep caddy

caddy启动失败(第二次)！退出安装！
journalctl -n50 --no-pager --boot -u  caddy
-- No entries --

caddy启动失败，原因如上！请排查原因！
发生错误，安装中断......

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/97840988-f8c84c00-1d1f-11eb-9d9b-6cbe1de1ec58.png)

**Comment by molun** [comment]
Caddy/NaiveProxy卸载失败！请向开发者问询！
检测系统是否已经安装MtProto......
if [[ -f /usr/local/bin/mtg ]];then echo '1';else echo '0'; fi
0

检测结果：未安装MtProto!
卸载成功！

**Comment by molun** [comment]
是没有卸载干净吗？

**Comment by proxysu** [comment]
是的，原来的Caddy没有卸载地干净，你可能需要把系统重装一下，再试试。

**Comment by proxysu** [comment]
如果还有问题，可以试一下这个最新的测试版。
https://github.com/proxysu/windows/raw/master/ProxySU/bin/Beta/Beta.zip

**Comment by molun** [comment]
> 如果还有问题，可以试一下这个最新的测试版。
> https://github.com/proxysu/windows/raw/master/ProxySU/bin/Beta/Beta.zip

![image](https://user-images.githubusercontent.com/23138506/97851447-5a90b200-1d30-11eb-9d8f-97b029ec55ff.png)
重置还不行，需要新建个实例吗

**Comment by proxysu** [comment]
是的，谷歌云的重置很奇怪，并不能完全将系统恢复到初始状态。

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/97859144-2242a100-1d3b-11eb-9c25-da90a26acaac.png)
新建了实例，这是等待升级吗？看不到进度了
![image](https://user-images.githubusercontent.com/23138506/97859223-443c2380-1d3b-11eb-9674-b5dd96c03320.png)
![image](https://user-images.githubusercontent.com/23138506/97861230-671c0700-1d3e-11eb-9ed0-b88aa39d0704.png)
半天没有反应

**Comment by proxysu** [comment]
这种情况，大多是vps连线不好，可能掉线了
