### ISSUE TITLE
请问如何配置多用户

### ISSUE THREAD

**Issue by Cstudent123** [proxysu/windows#57]
是这样,我用proxysu配置vless+xtls单用户非常成功,真的方便简直太方便了，我手工配置半天都不行。
然后现在配置好了我想给舍友一起用，那就需要配置多用户，请问proxysu面板支持这方面的操作吗？谢谢！

**Comment by Cstudent123** [comment]
当然不行的话我也可以进终端改config.json文件，问题不大我就是稍稍问一下，谢谢！

**Comment by proxysu** [comment]
这个功能看来要求的人挺多，已经加入到功能开发计划中，以后有时间，会实现。
当前，你可以自行修改config.json文件，实现多用户。
或者，还有一种方案，就是在ProxySU中添加一键安装，多用户管理面板，这样也可以实现管理配置多用户。

**Comment by Cstudent123** [comment]
好的非常感谢！ 这个程序真的帮了我大忙！

**Comment by lllrrr2** [comment]
多用户管理面板 好期待这个功能。

**Comment by showok** [comment]
> 这个功能看来要求的人挺多，已经加入到功能开发计划中，以后有时间，会实现。 当前，你可以自行修改config.json文件，实现多用户。 或者，还有一种方案，就是在ProxySU中添加一键安装，多用户管理面板，这样也可以实现管理配置多用户。

请问多用户管理面板有开发计划吗
