### ISSUE TITLE
为什么不支持window下搭建呢?

### ISSUE THREAD

**Issue by samcbc** [proxysu/windows#58]
那三个系统我都没有 好奇为什么一键搭建都没有在win的平台下的

**Comment by proxysu** [comment]
ProxySU使用的都是ssh登录vps，貌似windows的服务器，不支持这种远程登录方式吧？
另外配置文件是通用的，你可以把在linux下生成的配置文件，放到windows服务器中，使用v2ray的win版，运行加载就可以了。

**Comment by samcbc** [comment]
能否和生成到一个目录中 我拉去给win用呢 手上没有那三个系统 其实都不用登陆了 主要是不会配置的人多

**Comment by proxysu** [comment]
如果是简单的代理方案，可以只用其配置文件，但是复杂的，就不止一个配置文件，也不止一个软件了，比如v2ray+https+ws+web这个里面，不光有v2ray的配置，还有caddy的相关配置，你确定可以在windows系统的服务器上，完整配置？
目前整个科学上网的服务端生态，包括各种一键脚本，都是在linux系统下。用于Windows系统服务器的，几乎没有。ProxySU也是建立在其他一键脚本的基础上运行的，很难改变到用于windows中配置。。
如果你确实想在windows服务器上用，只能是自己去了解相关配置了。很报歉，恐怕帮不到你了
