### ISSUE TITLE
修改config.json多用户成功，但是按照官方教程修改多用户流量统计不成功，可否帮忙看一下哪里有问题，感谢

### ISSUE THREAD

**Issue by kobehuanghai** [proxysu/windows#60]
修改config.json多用户成功，但是按照官方教程修改多用户流量统计不成功，可否帮忙看一下哪里有问题，感谢

{
  "stats": {},
  "api": {
      "tag": "api",
      "services": [
          "StatsService"
      ]
  },
  "policy": {
    "levels": {
        "0": {
            "statsUserUplink": true,
            "statsUserDownlink": true
        }
    },
    "system": {
        "statsInboundUplink": true,
        "statsInboundDownlink": true
    }
  },
  "log": {
    "loglevel": "warning"
  },
  "dns": {},
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "inboundTag": [
            "api"
        ],
        "outboundTag": "api"
      }
    ]
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xxxxxxxxxxxxxxxxxxxxxx",
            "flow": "xtls-rprx-direct",
            "level": 0,
            "email": "xxx@xxxx.xxxx"
          },
          {
            "id": "xxxxxxxxxxxxxxxxxxxxxx",
            "flow": "xtls-rprx-direct",
            "level": 0,
            "email": "xxx@xxxx.xxxx"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 32434
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/usr/local/etc/v2ray/ssl/v2ray_ssl.crt",
              "keyFile": "/usr/local/etc/v2ray/ssl/v2ray_ssl.key"
            }
          ]
        }
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 10085,
      "protocol": "dokodemo-door",
      "settings": {
          "address": "127.0.0.1"
      },
      "tag": "api"
    }  
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "transport": {},
  "reverse": {}
}

**Comment by proxysu** [comment]
这个说明，不知道你看了没有，我对比了一下，你的配置是没有问题的。你可以换成vmess协议，再试试。
https://guide.v2fly.org/advanced/traffic.html#%E9%85%8D%E7%BD%AE%E7%BB%9F%E8%AE%A1%E5%8A%9F%E8%83%BD

**Comment by kobehuanghai** [comment]
> 这个说明，不知道你看了没有，我对比了一下，你的配置是没有问题的。你可以换成vmess协议，再试试。
> https://guide.v2fly.org/advanced/traffic.html#%E9%85%8D%E7%BD%AE%E7%BB%9F%E8%AE%A1%E5%8A%9F%E8%83%BD
> 我没有对统计数据做过研究，主要是个人使用，涉及到这方面的很少。可能无法提供更有价值的参考，抱歉。

感谢回复，我自己就是按照这个改的，那我再研究下，谢谢

**Comment by wuzhonglijz** [comment]
请问这个config.json是在哪个路径下面的？

**Comment by proxysu** [comment]
/usr/local/etc/v2ray/config.json
