### ISSUE TITLE
监控服务

### ISSUE THREAD

**Issue by xiaotianwl** [proxysu/windows#61]
希望做一个一键脚本  能监听服务器的CPU  内存  硬盘  流量 等一些监控的网站

**Comment by proxysu** [comment]
这个有很多面板和一键脚本可以实现，这方面的功能，并不是个人使用代理节点所必需的，但是未来不排除可能会增加这方面的功能，目前ProxySU还未有此功能计划。

**Comment by xiaotianwl** [comment]
好吧！  那我暂时用其他的面板看看吧！
