### ISSUE TITLE
“伪装网站” 功能怎么使用

### ISSUE THREAD

**Issue by onfootbug** [proxysu/windows#63]
Hi，你的这个工具真的是太好用了，小白想请教一下最近新增的 伪装网站 功能是怎么使用的，是要填入自己搭建的网址嘛？

**Comment by proxysu** [comment]
伪装网站是网上已经现存的任何网站，没有敏感信息的，没有被墙的国外网站都行，不需要自已搭建。只填域名，不要带 http 或 /。

**Comment by onfootbug** [comment]
了解了，多谢！
