### ISSUE TITLE
caddy v1已失效

### ISSUE THREAD

**Issue by Alvin9999** [proxysu/windows#7]
https://github.com/caddyserver/getcaddy.com/issues/45
caddy v1失效导致windows安装v2ray和naive都失效，但软件显示的是安装成功。

**Comment by proxysu** [comment]
好的，我尽快修复。谢谢

**Comment by Alvin9999** [comment]
@proxysu  反馈，trojan-go提示官方脚本安装出错，尝试了5次，换了系统也不行；trojan可以正常安装，只不过会一些小的报错提醒。trojan-go与caddy无关，有空还请您看下。
